// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_noise_gate_screen_init(void)
{
    ui_fx_noise_gate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_fx_noise_gate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fx_noise_gate, lv_color_hex(0x2D2F36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fx_noise_gate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_fx_name_2 = lv_label_create(ui_fx_noise_gate);
    lv_obj_set_width(ui_lbl_fx_name_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_fx_name_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_fx_name_2, 0);
    lv_obj_set_y(ui_lbl_fx_name_2, 10);
    lv_obj_set_align(ui_lbl_fx_name_2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_fx_name_2, "NOISE GATE");
    lv_obj_set_style_text_color(ui_lbl_fx_name_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_fx_name_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_fx_name_2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_noise_gate_bypass = lv_imgbtn_create(ui_fx_noise_gate);
    lv_imgbtn_set_src(ui_btn_noise_gate_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_noise_gate_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_noise_gate_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_noise_gate_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_noise_gate_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_noise_gate_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_width(ui_btn_noise_gate_bypass, 125);
    lv_obj_set_height(ui_btn_noise_gate_bypass, 94);
    lv_obj_set_x(ui_btn_noise_gate_bypass, 0);
    lv_obj_set_y(ui_btn_noise_gate_bypass, 5);
    lv_obj_set_align(ui_btn_noise_gate_bypass, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btn_noise_gate_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_lbl_noise_gate_bypass_btn = lv_label_create(ui_btn_noise_gate_bypass);
    lv_obj_set_width(ui_lbl_noise_gate_bypass_btn, 68);
    lv_obj_set_height(ui_lbl_noise_gate_bypass_btn, 19);
    lv_obj_set_align(ui_lbl_noise_gate_bypass_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_noise_gate_bypass_btn, "BYPASS");
    lv_obj_set_style_text_color(ui_lbl_noise_gate_bypass_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_noise_gate_bypass_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_noise_gate_bypass_btn, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_noise_gate_bypass_btn, &ui_font_mos_semibold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_noise_gate_bypass, ui_event_btn_noise_gate_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_noise_gate, ui_event_fx_noise_gate, LV_EVENT_ALL, NULL);

}
