// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: fx_tremolo

#include "ui.h"

void fx_tremolo_rate_changed(lv_event_t * e)
{
	// Your code here
}

void fx_tremolo_shape_changed(lv_event_t * e)
{
	// Your code here
}

void fx_tremolo_depth_changed(lv_event_t * e)
{
	// Your code here
}

void fx_tremolo_bypass(lv_event_t * e)
{
	// Your code here
}
