// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "ui.h"

void ui_fx_compressor_screen_init(void)
{
    ui_fx_compressor = lv_obj_create(NULL);

    ui_pnl_comp_content = lv_obj_create(ui_fx_compressor);
    lv_obj_set_width(ui_pnl_comp_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_comp_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_comp_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_comp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_comp_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_comp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_comp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_comp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_comp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_comp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_comp_fx_name = lv_label_create(ui_pnl_comp_content);
    lv_obj_set_width(ui_lbl_comp_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_comp_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_comp_fx_name, 0);
    lv_obj_set_y(ui_lbl_comp_fx_name, 10);
    lv_obj_set_align(ui_lbl_comp_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_comp_fx_name, "COMPRESSOR");
    lv_obj_set_style_text_color(ui_lbl_comp_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_comp_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_comp_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_comp_bypass = lv_imgbtn_create(ui_pnl_comp_content);
    lv_imgbtn_set_src(ui_btn_comp_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_comp_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_comp_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_comp_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_comp_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_comp_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_comp_bypass, 70);
    lv_obj_set_width(ui_btn_comp_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_comp_bypass, 15);
    lv_obj_set_y(ui_btn_comp_bypass, 0);
    lv_obj_set_align(ui_btn_comp_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_comp_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_comp_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_comp_bypass = lv_label_create(ui_btn_comp_bypass);
    lv_obj_set_width(ui_lbl_btn_comp_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_comp_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_comp_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_comp_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_comp_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_comp_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_comp_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_comp_controls = lv_obj_create(ui_pnl_comp_content);
    lv_obj_set_width(ui_pnl_comp_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_comp_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_comp_controls, 0);
    lv_obj_set_y(ui_pnl_comp_controls, 35);
    lv_obj_set_align(ui_pnl_comp_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_comp_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_comp_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_comp_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_comp_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Threshold control
    ui_pnl_comp_threshold = lv_obj_create(ui_pnl_comp_controls);
    lv_obj_set_width(ui_pnl_comp_threshold, lv_pct(33));
    lv_obj_set_height(ui_pnl_comp_threshold, lv_pct(50));
    lv_obj_set_x(ui_pnl_comp_threshold, 0);
    lv_obj_set_y(ui_pnl_comp_threshold, 0);
    lv_obj_set_align(ui_pnl_comp_threshold, LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(ui_pnl_comp_threshold, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_comp_threshold, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_threshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_comp_threshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_comp_threshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_comp_threshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_comp_threshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_comp_threshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_comp_threshold = lv_img_create(ui_pnl_comp_threshold);
    lv_img_set_src(ui_img_comp_threshold, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_comp_threshold, 70);
    lv_obj_set_height(ui_img_comp_threshold, 71);
    lv_obj_set_x(ui_img_comp_threshold, 0);
    lv_obj_set_y(ui_img_comp_threshold, -8);
    lv_obj_set_align(ui_img_comp_threshold, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_comp_threshold, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_comp_threshold = lv_arc_create(ui_pnl_comp_threshold);
    lv_obj_set_width(ui_arc_comp_threshold, 65);
    lv_obj_set_height(ui_arc_comp_threshold, 66);
    lv_obj_set_x(ui_arc_comp_threshold, 0);
    lv_obj_set_y(ui_arc_comp_threshold, -8);
    lv_obj_set_align(ui_arc_comp_threshold, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_comp_threshold, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_comp_threshold, -60, 0);
    lv_arc_set_value(ui_arc_comp_threshold, -20);
    lv_arc_set_bg_angles(ui_arc_comp_threshold, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_comp_threshold, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_threshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_threshold, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_comp_threshold, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_threshold, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_threshold, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_comp_threshold, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_comp_threshold, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_comp_threshold, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_comp_threshold = lv_label_create(ui_pnl_comp_threshold);
    lv_obj_set_width(ui_lbl_comp_threshold, 68);
    lv_obj_set_height(ui_lbl_comp_threshold, 17);
    lv_obj_set_align(ui_lbl_comp_threshold, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_comp_threshold, "THRESH");
    lv_obj_set_style_text_color(ui_lbl_comp_threshold, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_comp_threshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_comp_threshold, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_comp_threshold, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Ratio control
    ui_pnl_comp_ratio = lv_obj_create(ui_pnl_comp_controls);
    lv_obj_set_width(ui_pnl_comp_ratio, lv_pct(33));
    lv_obj_set_height(ui_pnl_comp_ratio, lv_pct(50));
    lv_obj_set_x(ui_pnl_comp_ratio, 0);
    lv_obj_set_y(ui_pnl_comp_ratio, 0);
    lv_obj_set_align(ui_pnl_comp_ratio, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_comp_ratio, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_comp_ratio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_ratio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_comp_ratio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_comp_ratio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_comp_ratio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_comp_ratio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_comp_ratio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_comp_ratio = lv_img_create(ui_pnl_comp_ratio);
    lv_img_set_src(ui_img_comp_ratio, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_comp_ratio, 70);
    lv_obj_set_height(ui_img_comp_ratio, 71);
    lv_obj_set_x(ui_img_comp_ratio, 0);
    lv_obj_set_y(ui_img_comp_ratio, -8);
    lv_obj_set_align(ui_img_comp_ratio, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_comp_ratio, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_comp_ratio = lv_arc_create(ui_pnl_comp_ratio);
    lv_obj_set_width(ui_arc_comp_ratio, 65);
    lv_obj_set_height(ui_arc_comp_ratio, 66);
    lv_obj_set_x(ui_arc_comp_ratio, 0);
    lv_obj_set_y(ui_arc_comp_ratio, -8);
    lv_obj_set_align(ui_arc_comp_ratio, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_comp_ratio, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_comp_ratio, 1, 20);
    lv_arc_set_value(ui_arc_comp_ratio, 4);
    lv_arc_set_bg_angles(ui_arc_comp_ratio, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_comp_ratio, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_ratio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_ratio, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_comp_ratio, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_ratio, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_ratio, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_comp_ratio, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_comp_ratio, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_comp_ratio, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_comp_ratio = lv_label_create(ui_pnl_comp_ratio);
    lv_obj_set_width(ui_lbl_comp_ratio, 68);
    lv_obj_set_height(ui_lbl_comp_ratio, 17);
    lv_obj_set_align(ui_lbl_comp_ratio, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_comp_ratio, "RATIO");
    lv_obj_set_style_text_color(ui_lbl_comp_ratio, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_comp_ratio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_comp_ratio, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_comp_ratio, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Attack control
    ui_pnl_comp_attack = lv_obj_create(ui_pnl_comp_controls);
    lv_obj_set_width(ui_pnl_comp_attack, lv_pct(33));
    lv_obj_set_height(ui_pnl_comp_attack, lv_pct(50));
    lv_obj_set_x(ui_pnl_comp_attack, 0);
    lv_obj_set_y(ui_pnl_comp_attack, 0);
    lv_obj_set_align(ui_pnl_comp_attack, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_pnl_comp_attack, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_comp_attack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_attack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_comp_attack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_comp_attack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_comp_attack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_comp_attack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_comp_attack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_comp_attack = lv_img_create(ui_pnl_comp_attack);
    lv_img_set_src(ui_img_comp_attack, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_comp_attack, 70);
    lv_obj_set_height(ui_img_comp_attack, 71);
    lv_obj_set_x(ui_img_comp_attack, 0);
    lv_obj_set_y(ui_img_comp_attack, -8);
    lv_obj_set_align(ui_img_comp_attack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_comp_attack, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_comp_attack = lv_arc_create(ui_pnl_comp_attack);
    lv_obj_set_width(ui_arc_comp_attack, 65);
    lv_obj_set_height(ui_arc_comp_attack, 66);
    lv_obj_set_x(ui_arc_comp_attack, 0);
    lv_obj_set_y(ui_arc_comp_attack, -8);
    lv_obj_set_align(ui_arc_comp_attack, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_comp_attack, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_comp_attack, 0, 100);
    lv_arc_set_value(ui_arc_comp_attack, 5);
    lv_arc_set_bg_angles(ui_arc_comp_attack, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_comp_attack, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_attack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_attack, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_comp_attack, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_attack, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_attack, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_comp_attack, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_comp_attack, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_comp_attack, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_comp_attack = lv_label_create(ui_pnl_comp_attack);
    lv_obj_set_width(ui_lbl_comp_attack, 68);
    lv_obj_set_height(ui_lbl_comp_attack, 17);
    lv_obj_set_align(ui_lbl_comp_attack, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_comp_attack, "ATTACK");
    lv_obj_set_style_text_color(ui_lbl_comp_attack, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_comp_attack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_comp_attack, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_comp_attack, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Release control (bottom left)
    ui_pnl_comp_release = lv_obj_create(ui_pnl_comp_controls);
    lv_obj_set_width(ui_pnl_comp_release, lv_pct(33));
    lv_obj_set_height(ui_pnl_comp_release, lv_pct(50));
    lv_obj_set_align(ui_pnl_comp_release, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_pnl_comp_release, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_comp_release, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_release, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_comp_release, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_comp_release, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_comp_release, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_comp_release, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_comp_release, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_comp_release = lv_img_create(ui_pnl_comp_release);
    lv_img_set_src(ui_img_comp_release, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_comp_release, 70);
    lv_obj_set_height(ui_img_comp_release, 71);
    lv_obj_set_x(ui_img_comp_release, 0);
    lv_obj_set_y(ui_img_comp_release, -8);
    lv_obj_set_align(ui_img_comp_release, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_comp_release, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_comp_release = lv_arc_create(ui_pnl_comp_release);
    lv_obj_set_width(ui_arc_comp_release, 65);
    lv_obj_set_height(ui_arc_comp_release, 66);
    lv_obj_set_x(ui_arc_comp_release, 0);
    lv_obj_set_y(ui_arc_comp_release, -8);
    lv_obj_set_align(ui_arc_comp_release, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_comp_release, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_comp_release, 10, 1000);
    lv_arc_set_value(ui_arc_comp_release, 100);
    lv_arc_set_bg_angles(ui_arc_comp_release, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_comp_release, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_release, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_release, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_comp_release, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_release, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_release, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_comp_release, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_comp_release, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_comp_release, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_comp_release = lv_label_create(ui_pnl_comp_release);
    lv_obj_set_width(ui_lbl_comp_release, 68);
    lv_obj_set_height(ui_lbl_comp_release, 17);
    lv_obj_set_align(ui_lbl_comp_release, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_comp_release, "RELEASE");
    lv_obj_set_style_text_color(ui_lbl_comp_release, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_comp_release, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_comp_release, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_comp_release, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Makeup Gain control (bottom center)
    ui_pnl_comp_makeup = lv_obj_create(ui_pnl_comp_controls);
    lv_obj_set_width(ui_pnl_comp_makeup, lv_pct(33));
    lv_obj_set_height(ui_pnl_comp_makeup, lv_pct(50));
    lv_obj_set_align(ui_pnl_comp_makeup, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_pnl_comp_makeup, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_comp_makeup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_makeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_comp_makeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_comp_makeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_comp_makeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_comp_makeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_comp_makeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_comp_makeup = lv_img_create(ui_pnl_comp_makeup);
    lv_img_set_src(ui_img_comp_makeup, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_comp_makeup, 70);
    lv_obj_set_height(ui_img_comp_makeup, 71);
    lv_obj_set_x(ui_img_comp_makeup, 0);
    lv_obj_set_y(ui_img_comp_makeup, -8);
    lv_obj_set_align(ui_img_comp_makeup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_comp_makeup, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_comp_makeup = lv_arc_create(ui_pnl_comp_makeup);
    lv_obj_set_width(ui_arc_comp_makeup, 65);
    lv_obj_set_height(ui_arc_comp_makeup, 66);
    lv_obj_set_x(ui_arc_comp_makeup, 0);
    lv_obj_set_y(ui_arc_comp_makeup, -8);
    lv_obj_set_align(ui_arc_comp_makeup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_comp_makeup, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_comp_makeup, 0, 30);
    lv_arc_set_value(ui_arc_comp_makeup, 10);
    lv_arc_set_bg_angles(ui_arc_comp_makeup, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_comp_makeup, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_makeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_makeup, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_comp_makeup, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_makeup, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_makeup, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_comp_makeup, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_comp_makeup, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_comp_makeup, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_comp_makeup = lv_label_create(ui_pnl_comp_makeup);
    lv_obj_set_width(ui_lbl_comp_makeup, 68);
    lv_obj_set_height(ui_lbl_comp_makeup, 17);
    lv_obj_set_align(ui_lbl_comp_makeup, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_comp_makeup, "MAKEUP");
    lv_obj_set_style_text_color(ui_lbl_comp_makeup, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_comp_makeup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_comp_makeup, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_comp_makeup, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Knee control (bottom right)
    ui_pnl_comp_knee = lv_obj_create(ui_pnl_comp_controls);
    lv_obj_set_width(ui_pnl_comp_knee, lv_pct(33));
    lv_obj_set_height(ui_pnl_comp_knee, lv_pct(50));
    lv_obj_set_align(ui_pnl_comp_knee, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_pnl_comp_knee, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_comp_knee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_comp_knee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_comp_knee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_comp_knee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_comp_knee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_comp_knee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_comp_knee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_comp_knee = lv_img_create(ui_pnl_comp_knee);
    lv_img_set_src(ui_img_comp_knee, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_comp_knee, 70);
    lv_obj_set_height(ui_img_comp_knee, 71);
    lv_obj_set_x(ui_img_comp_knee, 0);
    lv_obj_set_y(ui_img_comp_knee, -8);
    lv_obj_set_align(ui_img_comp_knee, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_comp_knee, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_comp_knee = lv_arc_create(ui_pnl_comp_knee);
    lv_obj_set_width(ui_arc_comp_knee, 65);
    lv_obj_set_height(ui_arc_comp_knee, 66);
    lv_obj_set_x(ui_arc_comp_knee, 0);
    lv_obj_set_y(ui_arc_comp_knee, -8);
    lv_obj_set_align(ui_arc_comp_knee, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_comp_knee, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_comp_knee, 0, 12);
    lv_arc_set_value(ui_arc_comp_knee, 6);
    lv_arc_set_bg_angles(ui_arc_comp_knee, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_comp_knee, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_knee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_knee, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_comp_knee, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_comp_knee, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_comp_knee, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_comp_knee, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_comp_knee, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_comp_knee, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_comp_knee = lv_label_create(ui_pnl_comp_knee);
    lv_obj_set_width(ui_lbl_comp_knee, 68);
    lv_obj_set_height(ui_lbl_comp_knee, 17);
    lv_obj_set_align(ui_lbl_comp_knee, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_comp_knee, "KNEE");
    lv_obj_set_style_text_color(ui_lbl_comp_knee, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_comp_knee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_comp_knee, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_comp_knee, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_comp_bypass, ui_event_btn_comp_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_comp_threshold, ui_event_arc_comp_threshold, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_comp_ratio, ui_event_arc_comp_ratio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_comp_attack, ui_event_arc_comp_attack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_comp_release, ui_event_arc_comp_release, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_comp_makeup, ui_event_arc_comp_makeup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_comp_knee, ui_event_arc_comp_knee, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_compressor, ui_event_fx_compressor, LV_EVENT_ALL, NULL);
}
