// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_set_user_data(void * user_data);
void ui_init_user_actions(void);
void ui_splash_loaded(lv_event_t * e);
void ui_effect_next(lv_event_t * e);
void ui_effect_prev(lv_event_t * e);
void ui_settings_dark_mode_changed(lv_event_t * e);
void ui_settings_display_brightess_changed(lv_event_t * e);
void ui_settings_in_vol_changed(lv_event_t * e);
void ui_settings_out_vol_changed(lv_event_t * e);
void ui_settings_mute_audio(lv_event_t * e);
void ui_settings_route_mic_to_aux(lv_event_t * e);
void ui_settings_usb_if_toggle(lv_event_t * e);
void ui_settings_usb_direct_mon(lv_event_t * e);
void ui_settings_add_effect(uint32_t new_effect_id);
void ui_settings_remove_effect(uint32_t effect_id);
void ui_settings_move_effect(uint32_t effect_id, int32_t dir);
void ui_settings_factory_reset(void);
void ui_settings_load_preset(const char * name);
void ui_settings_save_preset(const char * name);
void ui_settings_rename_preset(const char * old_name, const char * new_name);
void ui_settings_remove_preset(const char * name);
void ui_tuner_bypass(lv_event_t * e);
void ui_tremolo_bypass(lv_event_t * e);
void ui_tremolo_rate_changed(lv_event_t * e);
void ui_tremolo_depth_changed(lv_event_t * e);
void ui_tremolo_shape_changed(lv_event_t * e);
void ui_echo_bypass(lv_event_t * e);
void ui_echo_blur_changed(lv_event_t * e);
void ui_echo_feedb_changed(lv_event_t * e);
void ui_echo_time_changed(lv_event_t * e);
void ui_echo_mode_changed(lv_event_t * e);
void ui_chorus_bypass(lv_event_t * e);
void ui_chorus_mix_changed(lv_event_t * e);
void ui_chorus_rate_changed(lv_event_t * e);
void ui_chorus_depth_changed(lv_event_t * e);
void ui_chorus_mode_changed(lv_event_t * e);
void ui_reverb_bypass(lv_event_t * e);
void ui_reverb_bw_changed(lv_event_t * e);
void ui_reverb_damp_changed(lv_event_t * e);
void ui_reverb_decay_changed(lv_event_t * e);
void ui_reverb_mode_changed(lv_event_t * e);
void ui_overdrive_bypass(lv_event_t * e);
void ui_overdrive_mix_changed(lv_event_t * e);
void ui_overdrive_low_changed(lv_event_t * e);
void ui_overdrive_gain_changed(lv_event_t * e);
void ui_overdrive_high_changed(lv_event_t * e);
void ui_overdrive_mode_changed(lv_event_t * e);
void ui_cab_sim_bypass(lv_event_t * e);
void ui_cab_sim_ir_changed(lv_event_t * e);
void ui_vocoder_bypass(lv_event_t * e);
void ui_vocoder_clarity_changed(lv_event_t * e);
void ui_vocoder_tone_changed(lv_event_t * e);
void ui_vocoder_bands_changed(lv_event_t * e);
void ui_vocoder_mode_changed(lv_event_t * e);
void ui_vocoder_hold_changed(lv_event_t * e);
void ui_phaser_bypass(lv_event_t * e);
void ui_phaser_rate_changed(lv_event_t * e);
void ui_phaser_depth_changed(lv_event_t * e);
void ui_phaser_contour_changed(lv_event_t * e);
void ui_amp_sim_bypass(lv_event_t * e);
void ui_amp_sim_input_changed(lv_event_t * e);
void ui_amp_sim_drive_changed(lv_event_t * e);
void ui_amp_sim_compression_changed(lv_event_t * e);
void ui_amp_sim_bass_changed(lv_event_t * e);
void ui_amp_sim_mids_changed(lv_event_t * e);
void ui_amp_sim_treb_changed(lv_event_t * e);
void ui_amp_sim_mode_changed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
