// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "ui.h"

void ui_fx_arpeggiator_screen_init(void)
{
    ui_fx_arpeggiator = lv_obj_create(NULL);

    ui_pnl_arp_content = lv_obj_create(ui_fx_arpeggiator);
    lv_obj_set_width(ui_pnl_arp_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_arp_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_arp_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_arp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_arp_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_arp_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_arp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_arp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_arp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_arp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_arp_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_arp_fx_name = lv_label_create(ui_pnl_arp_content);
    lv_obj_set_width(ui_lbl_arp_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_arp_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_arp_fx_name, 0);
    lv_obj_set_y(ui_lbl_arp_fx_name, 10);
    lv_obj_set_align(ui_lbl_arp_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_arp_fx_name, "ARPEGGIATOR");
    lv_obj_set_style_text_color(ui_lbl_arp_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_arp_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_arp_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_arp_bypass = lv_imgbtn_create(ui_pnl_arp_content);
    lv_imgbtn_set_src(ui_btn_arp_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_arp_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_arp_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_arp_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_arp_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_arp_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_arp_bypass, 70);
    lv_obj_set_width(ui_btn_arp_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_arp_bypass, 15);
    lv_obj_set_y(ui_btn_arp_bypass, 0);
    lv_obj_set_align(ui_btn_arp_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_arp_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_arp_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_arp_bypass = lv_label_create(ui_btn_arp_bypass);
    lv_obj_set_width(ui_lbl_btn_arp_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_arp_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_arp_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_arp_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_arp_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_arp_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_arp_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_arp_controls = lv_obj_create(ui_pnl_arp_content);
    lv_obj_set_width(ui_pnl_arp_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_arp_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_arp_controls, 0);
    lv_obj_set_y(ui_pnl_arp_controls, 35);
    lv_obj_set_align(ui_pnl_arp_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_arp_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_arp_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_arp_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_arp_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_arp_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Rate control (left)
    ui_pnl_arp_rate = lv_obj_create(ui_pnl_arp_controls);
    lv_obj_set_width(ui_pnl_arp_rate, lv_pct(33));
    lv_obj_set_height(ui_pnl_arp_rate, lv_pct(100));
    lv_obj_set_align(ui_pnl_arp_rate, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pnl_arp_rate, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_arp_rate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_arp_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_arp_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_arp_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_arp_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_arp_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_arp_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_arp_rate = lv_img_create(ui_pnl_arp_rate);
    lv_img_set_src(ui_img_arp_rate, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_arp_rate, 104);
    lv_obj_set_height(ui_img_arp_rate, 105);
    lv_obj_set_x(ui_img_arp_rate, 0);
    lv_obj_set_y(ui_img_arp_rate, -12);
    lv_obj_set_align(ui_img_arp_rate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_arp_rate, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_arp_rate = lv_arc_create(ui_pnl_arp_rate);
    lv_obj_set_width(ui_arc_arp_rate, 95);
    lv_obj_set_height(ui_arc_arp_rate, 97);
    lv_obj_set_x(ui_arc_arp_rate, 0);
    lv_obj_set_y(ui_arc_arp_rate, -12);
    lv_obj_set_align(ui_arc_arp_rate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_arp_rate, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_arp_rate, 60, 240);
    lv_arc_set_value(ui_arc_arp_rate, 120);
    lv_arc_set_bg_angles(ui_arc_arp_rate, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_arp_rate, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_arp_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_arp_rate, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_arp_rate, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_arp_rate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_arp_rate, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_arp_rate, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_arp_rate, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_arp_rate, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_arp_rate = lv_label_create(ui_pnl_arp_rate);
    lv_obj_set_width(ui_lbl_arp_rate, 68);
    lv_obj_set_height(ui_lbl_arp_rate, 17);
    lv_obj_set_align(ui_lbl_arp_rate, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_arp_rate, "RATE");
    lv_obj_set_style_text_color(ui_lbl_arp_rate, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_arp_rate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_arp_rate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_arp_rate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Pattern dropdown (center)
    ui_pnl_arp_pattern = lv_obj_create(ui_pnl_arp_controls);
    lv_obj_set_width(ui_pnl_arp_pattern, lv_pct(33));
    lv_obj_set_height(ui_pnl_arp_pattern, lv_pct(100));
    lv_obj_set_align(ui_pnl_arp_pattern, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_arp_pattern, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_arp_pattern, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_arp_pattern, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_arp_pattern, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_arp_pattern, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_arp_pattern, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_arp_pattern, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_arp_pattern, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dd_arp_pattern = lv_roller_create(ui_pnl_arp_pattern);
    lv_roller_set_options(ui_dd_arp_pattern, "UP\nDOWN\nUP-DOWN\nRANDOM\nOCTAVE", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_dd_arp_pattern, 100);
    lv_roller_set_visible_row_count(ui_dd_arp_pattern, 3);
    lv_obj_set_x(ui_dd_arp_pattern, 0);
    lv_obj_set_y(ui_dd_arp_pattern, -10);
    lv_obj_set_align(ui_dd_arp_pattern, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_dd_arp_pattern, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dd_arp_pattern, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dd_arp_pattern, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dd_arp_pattern, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dd_arp_pattern, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dd_arp_pattern, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_dd_arp_pattern, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dd_arp_pattern, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dd_arp_pattern, lv_color_hex(0x50FF7D), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dd_arp_pattern, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_dd_arp_pattern, LV_OBJ_FLAG_GESTURE_BUBBLE);

    ui_lbl_arp_pattern = lv_label_create(ui_pnl_arp_pattern);
    lv_obj_set_width(ui_lbl_arp_pattern, 68);
    lv_obj_set_height(ui_lbl_arp_pattern, 17);
    lv_obj_set_align(ui_lbl_arp_pattern, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_arp_pattern, "PATTERN");
    lv_obj_set_style_text_color(ui_lbl_arp_pattern, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_arp_pattern, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_arp_pattern, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_arp_pattern, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Mix control (right)
    ui_pnl_arp_mix = lv_obj_create(ui_pnl_arp_controls);
    lv_obj_set_width(ui_pnl_arp_mix, lv_pct(33));
    lv_obj_set_height(ui_pnl_arp_mix, lv_pct(100));
    lv_obj_set_align(ui_pnl_arp_mix, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pnl_arp_mix, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_pnl_arp_mix, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_arp_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_arp_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_arp_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_arp_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_arp_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_arp_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_arp_mix = lv_img_create(ui_pnl_arp_mix);
    lv_img_set_src(ui_img_arp_mix, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_arp_mix, 104);
    lv_obj_set_height(ui_img_arp_mix, 105);
    lv_obj_set_x(ui_img_arp_mix, 0);
    lv_obj_set_y(ui_img_arp_mix, -12);
    lv_obj_set_align(ui_img_arp_mix, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_arp_mix, LV_OBJ_FLAG_ADV_HITTEST);

    ui_arc_arp_mix = lv_arc_create(ui_pnl_arp_mix);
    lv_obj_set_width(ui_arc_arp_mix, 95);
    lv_obj_set_height(ui_arc_arp_mix, 97);
    lv_obj_set_x(ui_arc_arp_mix, 0);
    lv_obj_set_y(ui_arc_arp_mix, -12);
    lv_obj_set_align(ui_arc_arp_mix, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_arp_mix, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_arc_set_range(ui_arc_arp_mix, 0, 100);
    lv_arc_set_value(ui_arc_arp_mix, 50);
    lv_arc_set_bg_angles(ui_arc_arp_mix, 129, 51);
    lv_obj_set_style_arc_color(ui_arc_arp_mix, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_arp_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_arp_mix, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_arp_mix, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_arp_mix, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_arp_mix, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_arp_mix, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arc_arp_mix, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_arp_mix, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_arp_mix = lv_label_create(ui_pnl_arp_mix);
    lv_obj_set_width(ui_lbl_arp_mix, 68);
    lv_obj_set_height(ui_lbl_arp_mix, 17);
    lv_obj_set_align(ui_lbl_arp_mix, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_arp_mix, "MIX");
    lv_obj_set_style_text_color(ui_lbl_arp_mix, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_arp_mix, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_arp_mix, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_arp_mix, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_arp_bypass, ui_event_btn_arp_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_arp_rate, ui_event_arc_arp_rate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dd_arp_pattern, ui_event_dd_arp_pattern, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_arp_mix, ui_event_arc_arp_mix, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_arpeggiator, ui_event_fx_arpeggiator, LV_EVENT_ALL, NULL);
}
