// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_blank_screen_init(void)
{
    ui_blank = lv_obj_create(NULL);

    ui_pnl_blank_content = lv_obj_create(ui_blank);
    lv_obj_set_width(ui_pnl_blank_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_blank_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_blank_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_blank_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_blank_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_blank_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnl_blank_content, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnl_blank_content, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_blank_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_blank_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_blank_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_blank_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_blank_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_blank_name = lv_label_create(ui_pnl_blank_content);
    lv_obj_set_width(ui_lbl_blank_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_blank_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_blank_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_blank_name, "NO EFFECTS");
    lv_obj_set_style_text_color(ui_lbl_blank_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_blank_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_blank_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_blank, ui_event_blank, LV_EVENT_ALL, NULL);
}
