// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_blank_screen_init(void)
{
    ui_blank = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_blank, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_lbl_blank = lv_label_create(ui_blank);
    lv_obj_set_width(ui_lbl_blank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_blank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_blank, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_blank, "PEDALBOARD IS EMPTY");

    lv_obj_add_event_cb(ui_blank, ui_event_blank, LV_EVENT_ALL, NULL);
}
