// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_chorus_screen_init(void)
{
    ui_fx_chorus = lv_obj_create(NULL);

    ui_pnl_chorus_content = lv_obj_create(ui_fx_chorus);
    lv_obj_set_width(ui_pnl_chorus_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_chorus_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_chorus_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_chorus_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_chorus_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_chorus_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnl_chorus_content, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnl_chorus_content, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_chorus_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_chorus_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_chorus_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_chorus_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_chorus_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_chorus_fx_name = lv_label_create(ui_pnl_chorus_content);
    lv_obj_set_width(ui_lbl_chorus_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_chorus_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_chorus_fx_name, 0);
    lv_obj_set_y(ui_lbl_chorus_fx_name, 10);
    lv_obj_set_align(ui_lbl_chorus_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_chorus_fx_name, "CHORUS");
    lv_obj_set_style_text_color(ui_lbl_chorus_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_chorus_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_chorus_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_chorus_bypass = lv_imgbtn_create(ui_pnl_chorus_content);
    lv_imgbtn_set_src(ui_btn_chorus_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_chorus_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_chorus_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_chorus_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_chorus_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_chorus_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_chorus_bypass, 70);
    lv_obj_set_width(ui_btn_chorus_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_chorus_bypass, 15);
    lv_obj_set_y(ui_btn_chorus_bypass, 0);
    lv_obj_set_align(ui_btn_chorus_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_chorus_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_chorus_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_chorus_bypass = lv_label_create(ui_btn_chorus_bypass);
    lv_obj_set_width(ui_lbl_btn_chorus_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_chorus_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_chorus_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_chorus_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_chorus_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_chorus_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_chorus_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_chorus_controls = lv_obj_create(ui_pnl_chorus_content);
    lv_obj_set_width(ui_pnl_chorus_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_chorus_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_chorus_controls, 0);
    lv_obj_set_y(ui_pnl_chorus_controls, 35);
    lv_obj_set_align(ui_pnl_chorus_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_chorus_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_chorus_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_chorus_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_chorus_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_chorus_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_chorus_mix = lv_obj_create(ui_pnl_chorus_controls);
    lv_obj_set_width(ui_pnl_chorus_mix, lv_pct(33));
    lv_obj_set_height(ui_pnl_chorus_mix, lv_pct(100));
    lv_obj_set_align(ui_pnl_chorus_mix, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pnl_chorus_mix,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_chorus_mix, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_chorus_mix = lv_img_create(ui_pnl_chorus_mix);
    lv_img_set_src(ui_img_chorus_mix, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_chorus_mix, 104);
    lv_obj_set_height(ui_img_chorus_mix, 105);
    lv_obj_set_x(ui_img_chorus_mix, 0);
    lv_obj_set_y(ui_img_chorus_mix, -12);
    lv_obj_set_align(ui_img_chorus_mix, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_chorus_mix, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_chorus_mix = lv_arc_create(ui_pnl_chorus_mix);
    lv_obj_set_width(ui_arc_chorus_mix, 95);
    lv_obj_set_height(ui_arc_chorus_mix, 97);
    lv_obj_set_x(ui_arc_chorus_mix, 0);
    lv_obj_set_y(ui_arc_chorus_mix, -12);
    lv_obj_set_align(ui_arc_chorus_mix, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_chorus_mix, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_chorus_mix, 0, 100);
    lv_arc_set_value(ui_arc_chorus_mix, 50);
    lv_arc_set_bg_angles(ui_arc_chorus_mix, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_chorus_mix, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_chorus_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_chorus_mix, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_chorus_mix, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_chorus_mix, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_chorus_mix, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_chorus_mix, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_chorus_mix, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_chorus_mix, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_chorus_mix = lv_label_create(ui_pnl_chorus_mix);
    lv_obj_set_width(ui_lbl_chorus_mix, 68);
    lv_obj_set_height(ui_lbl_chorus_mix, 17);
    lv_obj_set_align(ui_lbl_chorus_mix, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_chorus_mix, "MIX");
    lv_obj_set_style_text_color(ui_lbl_chorus_mix, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_chorus_mix, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_chorus_mix, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_chorus_mix, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_chorus_rate = lv_obj_create(ui_pnl_chorus_controls);
    lv_obj_set_width(ui_pnl_chorus_rate, lv_pct(33));
    lv_obj_set_height(ui_pnl_chorus_rate, lv_pct(100));
    lv_obj_set_align(ui_pnl_chorus_rate, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pnl_chorus_rate,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_chorus_rate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_chorus_rate = lv_img_create(ui_pnl_chorus_rate);
    lv_img_set_src(ui_img_chorus_rate, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_chorus_rate, 104);
    lv_obj_set_height(ui_img_chorus_rate, 105);
    lv_obj_set_x(ui_img_chorus_rate, 0);
    lv_obj_set_y(ui_img_chorus_rate, -12);
    lv_obj_set_align(ui_img_chorus_rate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_chorus_rate, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_chorus_rate = lv_arc_create(ui_pnl_chorus_rate);
    lv_obj_set_width(ui_arc_chorus_rate, 95);
    lv_obj_set_height(ui_arc_chorus_rate, 97);
    lv_obj_set_x(ui_arc_chorus_rate, 0);
    lv_obj_set_y(ui_arc_chorus_rate, -12);
    lv_obj_set_align(ui_arc_chorus_rate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_chorus_rate, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_chorus_rate, 5, 50);
    lv_arc_set_value(ui_arc_chorus_rate, 200);
    lv_arc_set_bg_angles(ui_arc_chorus_rate, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_chorus_rate, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_chorus_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_chorus_rate, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_chorus_rate, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_chorus_rate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_chorus_rate, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_chorus_rate, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_chorus_rate, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_chorus_rate, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_chorus_rate = lv_label_create(ui_pnl_chorus_rate);
    lv_obj_set_width(ui_lbl_chorus_rate, 100);
    lv_obj_set_height(ui_lbl_chorus_rate, 17);
    lv_obj_set_align(ui_lbl_chorus_rate, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_chorus_rate, "RATE");
    lv_obj_set_style_text_color(ui_lbl_chorus_rate, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_chorus_rate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_chorus_rate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_chorus_rate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_chorus_depth = lv_obj_create(ui_pnl_chorus_controls);
    lv_obj_set_width(ui_pnl_chorus_depth, lv_pct(33));
    lv_obj_set_height(ui_pnl_chorus_depth, lv_pct(100));
    lv_obj_set_align(ui_pnl_chorus_depth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_chorus_depth, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_chorus_depth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_chorus_depth = lv_img_create(ui_pnl_chorus_depth);
    lv_img_set_src(ui_img_chorus_depth, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_chorus_depth, 104);
    lv_obj_set_height(ui_img_chorus_depth, 105);
    lv_obj_set_x(ui_img_chorus_depth, 0);
    lv_obj_set_y(ui_img_chorus_depth, -12);
    lv_obj_set_align(ui_img_chorus_depth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_chorus_depth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_chorus_depth = lv_arc_create(ui_pnl_chorus_depth);
    lv_obj_set_width(ui_arc_chorus_depth, 95);
    lv_obj_set_height(ui_arc_chorus_depth, 97);
    lv_obj_set_x(ui_arc_chorus_depth, 0);
    lv_obj_set_y(ui_arc_chorus_depth, -12);
    lv_obj_set_align(ui_arc_chorus_depth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_chorus_depth, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_chorus_depth, 1, 30);
    lv_arc_set_value(ui_arc_chorus_depth, 20);
    lv_arc_set_bg_angles(ui_arc_chorus_depth, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_chorus_depth, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_chorus_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_chorus_depth, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_chorus_depth, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_chorus_depth, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_chorus_depth, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_chorus_depth, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_chorus_depth, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_chorus_depth, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_chorus_depth = lv_label_create(ui_pnl_chorus_depth);
    lv_obj_set_width(ui_lbl_chorus_depth, 68);
    lv_obj_set_height(ui_lbl_chorus_depth, 17);
    lv_obj_set_align(ui_lbl_chorus_depth, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_chorus_depth, "DEPTH");
    lv_obj_set_style_text_color(ui_lbl_chorus_depth, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_chorus_depth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_chorus_depth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_chorus_depth, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_chorus_mode = lv_obj_create(ui_pnl_chorus_content);
    lv_obj_set_width(ui_pnl_chorus_mode, lv_pct(40));
    lv_obj_set_height(ui_pnl_chorus_mode, lv_pct(14));
    lv_obj_set_x(ui_pnl_chorus_mode, 0);
    lv_obj_set_y(ui_pnl_chorus_mode, 100);
    lv_obj_set_align(ui_pnl_chorus_mode, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_chorus_mode, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_chorus_mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_chorus_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_chorus_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_chorus_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_chorus_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_chorus_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_chorus_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sw_chorus_mode = lv_switch_create(ui_pnl_chorus_mode);
    lv_obj_set_width(ui_sw_chorus_mode, 50);
    lv_obj_set_height(ui_sw_chorus_mode, 25);
    lv_obj_set_align(ui_sw_chorus_mode, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_sw_chorus_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_chorus_mode, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sw_chorus_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sw_chorus_mode, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_sw_chorus_mode, lv_color_hex(0x4C4E5B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_chorus_mode, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_chorus_mode_1 = lv_label_create(ui_pnl_chorus_mode);
    lv_obj_set_width(ui_lbl_chorus_mode_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_chorus_mode_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_chorus_mode_1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbl_chorus_mode_1, "MODE 1");
    lv_obj_set_style_text_color(ui_lbl_chorus_mode_1, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_chorus_mode_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_chorus_mode_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_chorus_mode_1, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_chorus_mode_1, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_chorus_mode_1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_add_state(ui_lbl_chorus_mode_1, LV_STATE_CHECKED);

    ui_lbl_chorus_mode_2 = lv_label_create(ui_pnl_chorus_mode);
    lv_obj_set_width(ui_lbl_chorus_mode_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_chorus_mode_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_chorus_mode_2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbl_chorus_mode_2, "MODE 2");
    lv_obj_set_style_text_color(ui_lbl_chorus_mode_2, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_chorus_mode_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_chorus_mode_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_chorus_mode_2, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_chorus_mode_2, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_chorus_mode_2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_btn_chorus_bypass, ui_event_btn_chorus_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_chorus_mix, ui_event_arc_chorus_mix, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_chorus_rate, ui_event_arc_chorus_rate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_chorus_depth, ui_event_arc_chorus_depth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sw_chorus_mode, ui_event_sw_chorus_mode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_chorus, ui_event_fx_chorus, LV_EVENT_ALL, NULL);

}
