// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

static void lv_bar_add_scale(lv_obj_t * bar, int min, int max, int step, bool vertical)
{
    lv_coord_t bar_x = lv_obj_get_x(bar);
    lv_coord_t bar_y = lv_obj_get_y(bar);
    lv_coord_t bar_w = lv_obj_get_width(bar) - 2;
    lv_coord_t bar_h = lv_obj_get_height(bar);

    int range = max - min;

    for (int value = min; value <= max; value += step) {
        float t = (float)(value - min) / range; // 0..1 fraction

        lv_coord_t tick_x, tick_y;
        if (vertical) {
            tick_x = bar_x + bar_w + 2;                 // tick on the right
            tick_y = bar_y + bar_h - (lv_coord_t)(t * bar_h); // top=0, bottom=bar_h
        } else {
            tick_x = bar_x + (lv_coord_t)(t * bar_w);
            tick_y = bar_y + bar_h + 2;               // tick below bar
        }

        // Tick mark
        lv_obj_t * tick = lv_obj_create(lv_obj_get_parent(bar));
        if (vertical)
            lv_obj_set_size(tick, 8, 2);             // horizontal tick for vertical bar
        else
            lv_obj_set_size(tick, 2, 8);             // vertical tick for horizontal bar

        lv_obj_set_style_bg_color(tick, lv_color_hex(0x747682), 0);
        lv_obj_set_style_border_width(tick, 0, 0);
        lv_obj_set_style_pad_all(tick, 0, 0);
        lv_obj_set_style_radius(tick, 0, 0);
        lv_obj_set_pos(tick, tick_x, tick_y);

        // Label
        lv_obj_t * label = lv_label_create(lv_obj_get_parent(bar));
        char buf[16];
        lv_snprintf(buf, sizeof(buf), "%d", value);
        lv_label_set_text(label, buf);
        lv_obj_set_style_text_color(label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

        if (vertical)
            lv_obj_align_to(label, tick, LV_ALIGN_OUT_RIGHT_MID, 2, 0);
        else
            lv_obj_align_to(label, tick, LV_ALIGN_OUT_BOTTOM_MID, 0, 0);
    }

    lv_obj_set_width(ui_bar_tuner_cents, lv_obj_get_width(bar) + 15);
}

void ui_fx_tuner_screen_init(void)
{
    ui_fx_tuner = lv_obj_create(NULL);

    ui_pnl_tuner_content = lv_obj_create(ui_fx_tuner);
    lv_obj_set_width(ui_pnl_tuner_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_tuner_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_tuner_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_tuner_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_tuner_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_tuner_fx_name = lv_label_create(ui_pnl_tuner_content);
    lv_obj_set_width(ui_lbl_tuner_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_tuner_fx_name, 0);
    lv_obj_set_y(ui_lbl_tuner_fx_name, 10);
    lv_obj_set_align(ui_lbl_tuner_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_tuner_fx_name, "CHROMATIC TUNER");
    lv_obj_set_style_text_color(ui_lbl_tuner_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_tuner_bypass = lv_imgbtn_create(ui_pnl_tuner_content);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_tuner_bypass, 70);
    lv_obj_set_width(ui_btn_tuner_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_tuner_bypass, 15);
    lv_obj_set_y(ui_btn_tuner_bypass, 0);
    lv_obj_set_align(ui_btn_tuner_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_tuner_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_tuner_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_tuner_bypass = lv_label_create(ui_btn_tuner_bypass);
    lv_obj_set_width(ui_lbl_btn_tuner_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_tuner_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_tuner_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_tuner_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_tuner_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_tuner_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_tuner_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_tuner_controls = lv_obj_create(ui_pnl_tuner_content);
    lv_obj_set_width(ui_pnl_tuner_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_tuner_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_tuner_controls, 0);
    lv_obj_set_y(ui_pnl_tuner_controls, 35);
    lv_obj_set_align(ui_pnl_tuner_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_tuner_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_tuner_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_tuner_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_tuner_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_tuner_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create bar
    ui_bar_tuner_cents = lv_bar_create(ui_pnl_tuner_controls);
    lv_obj_set_size(ui_bar_tuner_cents, 200, 19);
    lv_obj_center(ui_bar_tuner_cents);
    lv_obj_set_style_bg_color(ui_bar_tuner_cents, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_tuner_cents, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Bar indicator
    ui_bar_tuner_cents_indicator = lv_label_create(ui_pnl_tuner_controls);
    lv_obj_set_width(ui_bar_tuner_cents_indicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bar_tuner_cents_indicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_align_to(ui_bar_tuner_cents_indicator, ui_bar_tuner_cents, LV_ALIGN_CENTER, 10, -4);
    lv_label_set_text(ui_bar_tuner_cents_indicator, "|");
    lv_obj_set_style_text_color(ui_bar_tuner_cents_indicator, lv_color_hex(UI_PALETTE_SPRING_GREEN), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bar_tuner_cents_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bar_tuner_cents_indicator, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Bar scale
    lv_bar_add_scale(ui_bar_tuner_cents, -50, 50, 25, false);

    ui_lbl_tuner_pitch = lv_label_create(ui_pnl_tuner_controls);
    lv_obj_set_width(ui_lbl_tuner_pitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_pitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(ui_lbl_tuner_pitch, LV_ALIGN_TOP_MID, 0, 0);
    lv_label_set_text(ui_lbl_tuner_pitch, "-.-Hz");
    lv_obj_set_style_text_align(ui_lbl_tuner_pitch, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_color(ui_lbl_tuner_pitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_pitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_pitch, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_tuner_note = lv_label_create(ui_pnl_tuner_controls);
    lv_obj_set_width(ui_lbl_tuner_note, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_note, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(ui_lbl_tuner_note, LV_ALIGN_TOP_LEFT, 0, 0);
    lv_label_set_text(ui_lbl_tuner_note, "--");
    lv_obj_set_style_text_color(ui_lbl_tuner_note, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_note, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_note, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_tuner_cents = lv_label_create(ui_pnl_tuner_controls);
    lv_obj_set_width(ui_lbl_tuner_cents, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_cents, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(ui_lbl_tuner_cents, LV_ALIGN_TOP_RIGHT, 0, 0);
    lv_label_set_text(ui_lbl_tuner_cents, "-c");
    lv_obj_set_style_text_color(ui_lbl_tuner_cents, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_cents, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_cents, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_btn_tuner_bypass, ui_event_btn_tuner_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_tuner, ui_event_fx_tuner, LV_EVENT_ALL, NULL);

}
