// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

lv_obj_t * ui_fx_chorus_screen_create(void)
{
	   ui_scr_chorus = lv_obj_create(NULL);

    lv_obj_t * fx_base = ui_comp_fx_base(ui_scr_chorus, "CHORUS");
    lv_obj_t * fx_controls = ui_comp_fx_ctrl_pnl(fx_base);

    ui_btn_chorus_bypass = ui_comp_fx_btn(fx_base, "ON", LV_ALIGN_BOTTOM_LEFT);
    ui_arc_chorus_mix = ui_comp_fx_knob(fx_controls, "MIX", 0, 100, 50, LV_ALIGN_LEFT_MID);
    ui_arc_chorus_rate = ui_comp_fx_knob(fx_controls, "RATE", 0, 100, 50, LV_ALIGN_RIGHT_MID);
    ui_arc_chorus_depth = ui_comp_fx_knob(fx_controls, "DEPTH", 0, 100, 50, LV_ALIGN_CENTER);
    ui_sw_chorus_mode = ui_comp_fx_switch_create(fx_base, "WHITE", "DEEP  ");

    ui_comp_fx_switch_add_event_cb(ui_sw_chorus_mode, ui_event_sw_chorus_mode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn_chorus_bypass, ui_event_btn_chorus_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_chorus_mix, ui_event_arc_chorus_mix, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_chorus_rate, ui_event_arc_chorus_rate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_chorus_depth, ui_event_arc_chorus_depth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scr_chorus, ui_event_fx_chorus, LV_EVENT_ALL, NULL);

    return ui_scr_chorus;
}
