// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_echo_screen_init(void)
{
    ui_fx_echo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_fx_echo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fx_echo, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fx_echo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_fx_echo, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_fx_echo, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_echo_fx_name = lv_label_create(ui_fx_echo);
    lv_obj_set_width(ui_lbl_echo_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_echo_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_echo_fx_name, 0);
    lv_obj_set_y(ui_lbl_echo_fx_name, 10);
    lv_obj_set_align(ui_lbl_echo_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_echo_fx_name, "ECHO");
    lv_obj_set_style_text_color(ui_lbl_echo_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_echo_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_echo_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_echo_bypass = lv_imgbtn_create(ui_fx_echo);
    lv_imgbtn_set_src(ui_btn_echo_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_echo_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_echo_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_echo_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_echo_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_echo_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_echo_bypass, 70);
    lv_obj_set_width(ui_btn_echo_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_echo_bypass, 15);
    lv_obj_set_y(ui_btn_echo_bypass, 0);
    lv_obj_set_align(ui_btn_echo_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_echo_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_echo_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_echo_bypass = lv_label_create(ui_btn_echo_bypass);
    lv_obj_set_width(ui_lbl_btn_echo_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_echo_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_echo_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_echo_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_echo_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_echo_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_echo_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_echo_controls = lv_obj_create(ui_fx_echo);
    lv_obj_set_width(ui_pnl_echo_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_echo_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_echo_controls, 0);
    lv_obj_set_y(ui_pnl_echo_controls, 35);
    lv_obj_set_align(ui_pnl_echo_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_echo_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_echo_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_echo_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_echo_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_echo_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_echo_blur = lv_obj_create(ui_pnl_echo_controls);
    lv_obj_set_width(ui_pnl_echo_blur, lv_pct(33));
    lv_obj_set_height(ui_pnl_echo_blur, lv_pct(100));
    lv_obj_set_align(ui_pnl_echo_blur, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pnl_echo_blur,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_echo_blur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_echo_blur = lv_img_create(ui_pnl_echo_blur);
    lv_img_set_src(ui_img_echo_blur, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_echo_blur, 104);
    lv_obj_set_height(ui_img_echo_blur, 105);
    lv_obj_set_x(ui_img_echo_blur, 0);
    lv_obj_set_y(ui_img_echo_blur, -12);
    lv_obj_set_align(ui_img_echo_blur, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_echo_blur, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_echo_blur = lv_arc_create(ui_pnl_echo_blur);
    lv_obj_set_width(ui_arc_echo_blur, 95);
    lv_obj_set_height(ui_arc_echo_blur, 97);
    lv_obj_set_x(ui_arc_echo_blur, 0);
    lv_obj_set_y(ui_arc_echo_blur, -12);
    lv_obj_set_align(ui_arc_echo_blur, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_echo_blur, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_echo_blur, 0, 100);
    lv_arc_set_value(ui_arc_echo_blur, 50);
    lv_arc_set_bg_angles(ui_arc_echo_blur, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_echo_blur, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_echo_blur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_echo_blur, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_echo_blur, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_echo_blur, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_echo_blur, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_echo_blur, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_echo_blur, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_echo_blur, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_echo_blur = lv_label_create(ui_pnl_echo_blur);
    lv_obj_set_width(ui_lbl_echo_blur, 68);
    lv_obj_set_height(ui_lbl_echo_blur, 17);
    lv_obj_set_align(ui_lbl_echo_blur, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_echo_blur, "BLUR");
    lv_obj_set_style_text_color(ui_lbl_echo_blur, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_echo_blur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_echo_blur, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_echo_blur, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_echo_feedb = lv_obj_create(ui_pnl_echo_controls);
    lv_obj_set_width(ui_pnl_echo_feedb, lv_pct(33));
    lv_obj_set_height(ui_pnl_echo_feedb, lv_pct(100));
    lv_obj_set_align(ui_pnl_echo_feedb, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pnl_echo_feedb,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_echo_feedb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_echo_feedb = lv_img_create(ui_pnl_echo_feedb);
    lv_img_set_src(ui_img_echo_feedb, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_echo_feedb, 104);
    lv_obj_set_height(ui_img_echo_feedb, 105);
    lv_obj_set_x(ui_img_echo_feedb, 0);
    lv_obj_set_y(ui_img_echo_feedb, -12);
    lv_obj_set_align(ui_img_echo_feedb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_echo_feedb, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_echo_feedb = lv_arc_create(ui_pnl_echo_feedb);
    lv_obj_set_width(ui_arc_echo_feedb, 95);
    lv_obj_set_height(ui_arc_echo_feedb, 97);
    lv_obj_set_x(ui_arc_echo_feedb, 0);
    lv_obj_set_y(ui_arc_echo_feedb, -12);
    lv_obj_set_align(ui_arc_echo_feedb, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_echo_feedb, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_echo_feedb, 0, 100);
    lv_arc_set_value(ui_arc_echo_feedb, 60);
    lv_arc_set_bg_angles(ui_arc_echo_feedb, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_echo_feedb, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_echo_feedb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_echo_feedb, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_echo_feedb, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_echo_feedb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_echo_feedb, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_echo_feedb, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_echo_feedb, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_echo_feedb, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_echo_feedb = lv_label_create(ui_pnl_echo_feedb);
    lv_obj_set_width(ui_lbl_echo_feedb, 100);
    lv_obj_set_height(ui_lbl_echo_feedb, 17);
    lv_obj_set_align(ui_lbl_echo_feedb, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_echo_feedb, "FEEDBACK");
    lv_obj_set_style_text_color(ui_lbl_echo_feedb, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_echo_feedb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_echo_feedb, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_echo_feedb, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_echo_time = lv_obj_create(ui_pnl_echo_controls);
    lv_obj_set_width(ui_pnl_echo_time, lv_pct(33));
    lv_obj_set_height(ui_pnl_echo_time, lv_pct(100));
    lv_obj_set_align(ui_pnl_echo_time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_echo_time, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_echo_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_echo_time = lv_img_create(ui_pnl_echo_time);
    lv_img_set_src(ui_img_echo_time, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_echo_time, 104);
    lv_obj_set_height(ui_img_echo_time, 105);
    lv_obj_set_x(ui_img_echo_time, 0);
    lv_obj_set_y(ui_img_echo_time, -12);
    lv_obj_set_align(ui_img_echo_time, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_echo_time, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_echo_time = lv_arc_create(ui_pnl_echo_time);
    lv_obj_set_width(ui_arc_echo_time, 95);
    lv_obj_set_height(ui_arc_echo_time, 97);
    lv_obj_set_x(ui_arc_echo_time, 0);
    lv_obj_set_y(ui_arc_echo_time, -12);
    lv_obj_set_align(ui_arc_echo_time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_echo_time, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_echo_time, 5, 100);
    lv_arc_set_value(ui_arc_echo_time, 30);
    lv_arc_set_bg_angles(ui_arc_echo_time, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_echo_time, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_echo_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_echo_time, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_echo_time, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_echo_time, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_echo_time, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_echo_time, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_echo_time, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_echo_time, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_echo_time = lv_label_create(ui_pnl_echo_time);
    lv_obj_set_width(ui_lbl_echo_time, 68);
    lv_obj_set_height(ui_lbl_echo_time, 17);
    lv_obj_set_align(ui_lbl_echo_time, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_echo_time, "TIME");
    lv_obj_set_style_text_color(ui_lbl_echo_time, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_echo_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_echo_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_echo_time, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_echo_mode = lv_obj_create(ui_fx_echo);
    lv_obj_set_width(ui_pnl_echo_mode, lv_pct(36));
    lv_obj_set_height(ui_pnl_echo_mode, lv_pct(14));
    lv_obj_set_x(ui_pnl_echo_mode, 0);
    lv_obj_set_y(ui_pnl_echo_mode, 100);
    lv_obj_set_align(ui_pnl_echo_mode, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_echo_mode, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_echo_mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_echo_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_echo_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_echo_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_echo_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_echo_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_echo_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sw_echo_mode = lv_switch_create(ui_pnl_echo_mode);
    lv_obj_set_width(ui_sw_echo_mode, 50);
    lv_obj_set_height(ui_sw_echo_mode, 25);
    lv_obj_set_align(ui_sw_echo_mode, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_sw_echo_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_echo_mode, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sw_echo_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sw_echo_mode, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_sw_echo_mode, lv_color_hex(0x4C4E5B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_echo_mode, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_echo_mode_echo = lv_label_create(ui_pnl_echo_mode);
    lv_obj_set_width(ui_lbl_echo_mode_echo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_echo_mode_echo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_echo_mode_echo, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbl_echo_mode_echo, " ECHO");
    lv_obj_set_style_text_color(ui_lbl_echo_mode_echo, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_echo_mode_echo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_echo_mode_echo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_echo_mode_echo, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_echo_mode_echo, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_echo_mode_echo, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_add_state(ui_lbl_echo_mode_echo, LV_STATE_CHECKED);

    ui_lbl_echo_mode_delay = lv_label_create(ui_pnl_echo_mode);
    lv_obj_set_width(ui_lbl_echo_mode_delay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_echo_mode_delay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_echo_mode_delay, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbl_echo_mode_delay, "DELAY");
    lv_obj_set_style_text_color(ui_lbl_echo_mode_delay, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_echo_mode_delay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_echo_mode_delay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_echo_mode_delay, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_echo_mode_delay, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_echo_mode_delay, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_btn_echo_bypass, ui_event_btn_echo_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_echo_blur, ui_event_arc_echo_blur, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_echo_feedb, ui_event_arc_echo_feedb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_echo_time, ui_event_arc_echo_time, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sw_echo_mode, ui_event_sw_echo_mode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_echo, ui_event_fx_echo, LV_EVENT_ALL, NULL);

}
