// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_cabinet_sim_screen_init(void)
{
    ui_fx_cabinet_sim = lv_obj_create(NULL);

    ui_pnl_cab_sim_content = lv_obj_create(ui_fx_cabinet_sim);
    lv_obj_set_width(ui_pnl_cab_sim_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_cab_sim_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_cab_sim_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_cab_sim_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_cab_sim_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_cab_sim_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnl_cab_sim_content, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnl_cab_sim_content, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_cab_sim_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_cab_sim_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_cab_sim_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_cab_sim_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_cab_sim_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_cab_sim_fx_name = lv_label_create(ui_pnl_cab_sim_content);
    lv_obj_set_width(ui_lbl_cab_sim_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_cab_sim_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_cab_sim_fx_name, 0);
    lv_obj_set_y(ui_lbl_cab_sim_fx_name, 10);
    lv_obj_set_align(ui_lbl_cab_sim_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_cab_sim_fx_name, "CABINET SIM");
    lv_obj_set_style_text_color(ui_lbl_cab_sim_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_cab_sim_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_cab_sim_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_cab_sim_bypass = lv_imgbtn_create(ui_pnl_cab_sim_content);
    lv_imgbtn_set_src(ui_btn_cab_sim_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_cab_sim_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_cab_sim_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_cab_sim_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_cab_sim_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_cab_sim_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_cab_sim_bypass, 70);
    lv_obj_set_width(ui_btn_cab_sim_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_cab_sim_bypass, 15);
    lv_obj_set_y(ui_btn_cab_sim_bypass, 0);
    lv_obj_set_align(ui_btn_cab_sim_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_cab_sim_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_cab_sim_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_cab_sim_bypass = lv_label_create(ui_btn_cab_sim_bypass);
    lv_obj_set_width(ui_lbl_btn_cab_sim_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_cab_sim_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_cab_sim_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_cab_sim_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_cab_sim_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_cab_sim_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_cab_sim_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roller_cab_sim_ir = lv_roller_create(ui_pnl_cab_sim_content);
    lv_obj_set_width(ui_roller_cab_sim_ir, lv_pct(50));
    lv_obj_set_height(ui_roller_cab_sim_ir, lv_pct(40));
    lv_obj_set_align(ui_roller_cab_sim_ir, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_roller_cab_sim_ir, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller_cab_sim_ir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_cab_sim_ir, lv_color_hex(0x25272E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_cab_sim_ir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_roller_cab_sim_ir, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_roller_cab_sim_ir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_roller_cab_sim_ir, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller_cab_sim_ir, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_cab_sim_ir, lv_color_hex(0x50FF7D), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_cab_sim_ir, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_roller_cab_sim_ir, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_cab_sim_ir = lv_label_create(ui_pnl_cab_sim_content);
    lv_obj_set_width(ui_lbl_cab_sim_ir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_cab_sim_ir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_cab_sim_ir, 0);
    lv_obj_set_y(ui_lbl_cab_sim_ir, 60);
    lv_obj_set_align(ui_lbl_cab_sim_ir, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_cab_sim_ir, "IMPULSE RESPONSES");
    lv_obj_set_style_text_color(ui_lbl_cab_sim_ir, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_cab_sim_ir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_cab_sim_ir, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_cab_sim_bypass, ui_event_btn_cab_sim_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_roller_cab_sim_ir, ui_event_roller_cab_sim_ir, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_cabinet_sim, ui_event_fx_cabinet_sim, LV_EVENT_ALL, NULL);

}
