// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_reverb_screen_init(void)
{
    ui_fx_reverb = lv_obj_create(NULL);

    ui_pnl_reverb_content = lv_obj_create(ui_fx_reverb);
    lv_obj_set_width(ui_pnl_reverb_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_reverb_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_reverb_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_reverb_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_reverb_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_reverb_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnl_reverb_content, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_pnl_reverb_content, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_reverb_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_reverb_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_reverb_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_reverb_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_reverb_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_reverb_fx_name = lv_label_create(ui_pnl_reverb_content);
    lv_obj_set_width(ui_lbl_reverb_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_reverb_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_reverb_fx_name, 0);
    lv_obj_set_y(ui_lbl_reverb_fx_name, 10);
    lv_obj_set_align(ui_lbl_reverb_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_reverb_fx_name, "REVERB");
    lv_obj_set_style_text_color(ui_lbl_reverb_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_reverb_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_reverb_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_reverb_bypass = lv_imgbtn_create(ui_pnl_reverb_content);
    lv_imgbtn_set_src(ui_btn_reverb_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_reverb_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_reverb_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_reverb_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_reverb_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_reverb_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_reverb_bypass, 70);
    lv_obj_set_width(ui_btn_reverb_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_reverb_bypass, 15);
    lv_obj_set_y(ui_btn_reverb_bypass, 0);
    lv_obj_set_align(ui_btn_reverb_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_reverb_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_reverb_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_reverb_bypass = lv_label_create(ui_btn_reverb_bypass);
    lv_obj_set_width(ui_lbl_btn_reverb_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_reverb_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_reverb_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_reverb_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_reverb_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_reverb_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_reverb_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_reverb_controls = lv_obj_create(ui_pnl_reverb_content);
    lv_obj_set_width(ui_pnl_reverb_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_reverb_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_reverb_controls, 0);
    lv_obj_set_y(ui_pnl_reverb_controls, 35);
    lv_obj_set_align(ui_pnl_reverb_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_reverb_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_reverb_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_reverb_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_reverb_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_reverb_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_reverb_bw = lv_obj_create(ui_pnl_reverb_controls);
    lv_obj_set_width(ui_pnl_reverb_bw, lv_pct(33));
    lv_obj_set_height(ui_pnl_reverb_bw, lv_pct(100));
    lv_obj_set_align(ui_pnl_reverb_bw, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pnl_reverb_bw,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_reverb_bw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_reverb_bw = lv_img_create(ui_pnl_reverb_bw);
    lv_img_set_src(ui_img_reverb_bw, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_reverb_bw, 104);
    lv_obj_set_height(ui_img_reverb_bw, 105);
    lv_obj_set_x(ui_img_reverb_bw, 0);
    lv_obj_set_y(ui_img_reverb_bw, -12);
    lv_obj_set_align(ui_img_reverb_bw, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_reverb_bw, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_reverb_bw = lv_arc_create(ui_pnl_reverb_bw);
    lv_obj_set_width(ui_arc_reverb_bw, 95);
    lv_obj_set_height(ui_arc_reverb_bw, 97);
    lv_obj_set_x(ui_arc_reverb_bw, 0);
    lv_obj_set_y(ui_arc_reverb_bw, -12);
    lv_obj_set_align(ui_arc_reverb_bw, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_reverb_bw, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_reverb_bw, 0, 100);
    lv_arc_set_value(ui_arc_reverb_bw, 50);
    lv_arc_set_bg_angles(ui_arc_reverb_bw, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_reverb_bw, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_reverb_bw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_reverb_bw, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_reverb_bw, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_reverb_bw, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_reverb_bw, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_reverb_bw, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_reverb_bw, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_reverb_bw, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_reverb_bw = lv_label_create(ui_pnl_reverb_bw);
    lv_obj_set_width(ui_lbl_reverb_bw, 68);
    lv_obj_set_height(ui_lbl_reverb_bw, 17);
    lv_obj_set_align(ui_lbl_reverb_bw, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_reverb_bw, "BANDWIDTH");
    lv_obj_set_style_text_color(ui_lbl_reverb_bw, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_reverb_bw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_reverb_bw, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_reverb_bw, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_reverb_damp = lv_obj_create(ui_pnl_reverb_controls);
    lv_obj_set_width(ui_pnl_reverb_damp, lv_pct(33));
    lv_obj_set_height(ui_pnl_reverb_damp, lv_pct(100));
    lv_obj_set_align(ui_pnl_reverb_damp, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pnl_reverb_damp,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_reverb_damp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_reverb_damp = lv_img_create(ui_pnl_reverb_damp);
    lv_img_set_src(ui_img_reverb_damp, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_reverb_damp, 104);
    lv_obj_set_height(ui_img_reverb_damp, 105);
    lv_obj_set_x(ui_img_reverb_damp, 0);
    lv_obj_set_y(ui_img_reverb_damp, -12);
    lv_obj_set_align(ui_img_reverb_damp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_reverb_damp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_reverb_damp = lv_arc_create(ui_pnl_reverb_damp);
    lv_obj_set_width(ui_arc_reverb_damp, 95);
    lv_obj_set_height(ui_arc_reverb_damp, 97);
    lv_obj_set_x(ui_arc_reverb_damp, 0);
    lv_obj_set_y(ui_arc_reverb_damp, -12);
    lv_obj_set_align(ui_arc_reverb_damp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_reverb_damp, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_reverb_damp, 0, 100);
    lv_arc_set_value(ui_arc_reverb_damp, 50);
    lv_arc_set_bg_angles(ui_arc_reverb_damp, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_reverb_damp, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_reverb_damp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_reverb_damp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_reverb_damp, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_reverb_damp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_reverb_damp, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_reverb_damp, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_reverb_damp, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_reverb_damp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_reverb_damp = lv_label_create(ui_pnl_reverb_damp);
    lv_obj_set_width(ui_lbl_reverb_damp, 100);
    lv_obj_set_height(ui_lbl_reverb_damp, 17);
    lv_obj_set_align(ui_lbl_reverb_damp, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_reverb_damp, "DAMPING");
    lv_obj_set_style_text_color(ui_lbl_reverb_damp, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_reverb_damp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_reverb_damp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_reverb_damp, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_reverb_decay = lv_obj_create(ui_pnl_reverb_controls);
    lv_obj_set_width(ui_pnl_reverb_decay, lv_pct(33));
    lv_obj_set_height(ui_pnl_reverb_decay, lv_pct(100));
    lv_obj_set_align(ui_pnl_reverb_decay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_reverb_decay, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_reverb_decay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_reverb_decay = lv_img_create(ui_pnl_reverb_decay);
    lv_img_set_src(ui_img_reverb_decay, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_reverb_decay, 104);
    lv_obj_set_height(ui_img_reverb_decay, 105);
    lv_obj_set_x(ui_img_reverb_decay, 0);
    lv_obj_set_y(ui_img_reverb_decay, -12);
    lv_obj_set_align(ui_img_reverb_decay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_reverb_decay, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_reverb_decay = lv_arc_create(ui_pnl_reverb_decay);
    lv_obj_set_width(ui_arc_reverb_decay, 95);
    lv_obj_set_height(ui_arc_reverb_decay, 97);
    lv_obj_set_x(ui_arc_reverb_decay, 0);
    lv_obj_set_y(ui_arc_reverb_decay, -12);
    lv_obj_set_align(ui_arc_reverb_decay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_reverb_decay, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_reverb_decay, 0, 100);
    lv_arc_set_value(ui_arc_reverb_decay, 50);
    lv_arc_set_bg_angles(ui_arc_reverb_decay, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_reverb_decay, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_reverb_decay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_reverb_decay, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_reverb_decay, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_reverb_decay, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_reverb_decay, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_reverb_decay, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_reverb_decay, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_reverb_decay, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_reverb_decay = lv_label_create(ui_pnl_reverb_decay);
    lv_obj_set_width(ui_lbl_reverb_decay, 68);
    lv_obj_set_height(ui_lbl_reverb_decay, 17);
    lv_obj_set_align(ui_lbl_reverb_decay, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_reverb_decay, "DECAY");
    lv_obj_set_style_text_color(ui_lbl_reverb_decay, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_reverb_decay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_reverb_decay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_reverb_decay, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_reverb_mode = lv_obj_create(ui_pnl_reverb_content);
    lv_obj_set_width(ui_pnl_reverb_mode, lv_pct(45));
    lv_obj_set_height(ui_pnl_reverb_mode, lv_pct(14));
    lv_obj_set_x(ui_pnl_reverb_mode, 0);
    lv_obj_set_y(ui_pnl_reverb_mode, 100);
    lv_obj_set_align(ui_pnl_reverb_mode, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_reverb_mode, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_reverb_mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_reverb_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_reverb_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_reverb_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_reverb_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_reverb_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_reverb_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sw_reverb_mode = lv_switch_create(ui_pnl_reverb_mode);
    lv_obj_set_width(ui_sw_reverb_mode, 50);
    lv_obj_set_height(ui_sw_reverb_mode, 25);
    lv_obj_set_align(ui_sw_reverb_mode, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_sw_reverb_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_reverb_mode, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sw_reverb_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sw_reverb_mode, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_sw_reverb_mode, lv_color_hex(0x4C4E5B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_reverb_mode, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_reverb_mode_plate = lv_label_create(ui_pnl_reverb_mode);
    lv_obj_set_width(ui_lbl_reverb_mode_plate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_reverb_mode_plate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_reverb_mode_plate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbl_reverb_mode_plate, "    PLATE");
    lv_obj_set_style_text_color(ui_lbl_reverb_mode_plate, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_reverb_mode_plate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_reverb_mode_plate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_reverb_mode_plate, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_reverb_mode_plate, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_reverb_mode_plate, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_add_state(ui_lbl_reverb_mode_plate, LV_STATE_CHECKED);

    ui_lbl_reverb_mode_shimmer = lv_label_create(ui_pnl_reverb_mode);
    lv_obj_set_width(ui_lbl_reverb_mode_shimmer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_reverb_mode_shimmer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_reverb_mode_shimmer, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbl_reverb_mode_shimmer, "SHIMMER");
    lv_obj_set_style_text_color(ui_lbl_reverb_mode_shimmer, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_reverb_mode_shimmer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_reverb_mode_shimmer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_reverb_mode_shimmer, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_reverb_mode_shimmer, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_reverb_mode_shimmer, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_btn_reverb_bypass, ui_event_btn_reverb_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_reverb_bw, ui_event_arc_reverb_bw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_reverb_damp, ui_event_arc_reverb_damp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_reverb_decay, ui_event_arc_reverb_decay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sw_reverb_mode, ui_event_sw_reverb_mode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_reverb, ui_event_fx_reverb, LV_EVENT_ALL, NULL);

}
