// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_overdrive_screen_init(void)
{
    ui_fx_overdrive = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_fx_overdrive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fx_overdrive, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fx_overdrive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_fx_overdrive, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_fx_overdrive, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_od_fx_name = lv_label_create(ui_fx_overdrive);
    lv_obj_set_width(ui_lbl_od_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_od_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_od_fx_name, 0);
    lv_obj_set_y(ui_lbl_od_fx_name, 10);
    lv_obj_set_align(ui_lbl_od_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_od_fx_name, "OVERDRIVE");
    lv_obj_set_style_text_color(ui_lbl_od_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_od_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_od_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_od_bypass = lv_imgbtn_create(ui_fx_overdrive);
    lv_imgbtn_set_src(ui_btn_od_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_od_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_od_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_od_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_od_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_obj_set_height(ui_btn_od_bypass, 70);
    lv_obj_set_width(ui_btn_od_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_od_bypass, 15);
    lv_obj_set_y(ui_btn_od_bypass, 0);
    lv_obj_set_align(ui_btn_od_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_od_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_od_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_od_bypass = lv_label_create(ui_btn_od_bypass);
    lv_obj_set_width(ui_lbl_btn_od_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_od_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_od_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_od_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_od_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_od_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_od_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_od_controls = lv_obj_create(ui_fx_overdrive);
    lv_obj_set_width(ui_pnl_od_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_od_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_od_controls, 0);
    lv_obj_set_y(ui_pnl_od_controls, 35);
    lv_obj_set_align(ui_pnl_od_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_od_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_od_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_od_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_od_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_od_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_od_mix = lv_obj_create(ui_pnl_od_controls);
    lv_obj_set_width(ui_pnl_od_mix, lv_pct(33));
    lv_obj_set_height(ui_pnl_od_mix, lv_pct(100));
    lv_obj_set_align(ui_pnl_od_mix, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pnl_od_mix,
                     LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                     LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_od_mix, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_od_mix = lv_img_create(ui_pnl_od_mix);
    lv_img_set_src(ui_img_od_mix, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_od_mix, 104);
    lv_obj_set_height(ui_img_od_mix, 105);
    lv_obj_set_x(ui_img_od_mix, 0);
    lv_obj_set_y(ui_img_od_mix, -12);
    lv_obj_set_align(ui_img_od_mix, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_od_mix, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_od_mix = lv_arc_create(ui_pnl_od_mix);
    lv_obj_set_width(ui_arc_od_mix, 95);
    lv_obj_set_height(ui_arc_od_mix, 97);
    lv_obj_set_x(ui_arc_od_mix, 0);
    lv_obj_set_y(ui_arc_od_mix, -12);
    lv_obj_set_align(ui_arc_od_mix, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_od_mix, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_od_mix, 0, 100);
    lv_arc_set_value(ui_arc_od_mix, 50);
    lv_arc_set_bg_angles(ui_arc_od_mix, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_od_mix, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_od_mix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_od_mix, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_od_mix, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_od_mix, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_od_mix, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_od_mix, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_od_mix, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_od_mix, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_od_mix = lv_label_create(ui_pnl_od_mix);
    lv_obj_set_width(ui_lbl_od_mix, 68);
    lv_obj_set_height(ui_lbl_od_mix, 17);
    lv_obj_set_align(ui_lbl_od_mix, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_od_mix, "MIX");
    lv_obj_set_style_text_color(ui_lbl_od_mix, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_od_mix, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_od_mix, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_od_mix, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_od_tone = lv_obj_create(ui_pnl_od_controls);
    lv_obj_set_width(ui_pnl_od_tone, lv_pct(33));
    lv_obj_set_height(ui_pnl_od_tone, lv_pct(100));
    lv_obj_set_align(ui_pnl_od_tone, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pnl_od_tone,
                     LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                     LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_od_tone, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_od_tone = lv_img_create(ui_pnl_od_tone);
    lv_img_set_src(ui_img_od_tone, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_od_tone, 104);
    lv_obj_set_height(ui_img_od_tone, 105);
    lv_obj_set_x(ui_img_od_tone, 0);
    lv_obj_set_y(ui_img_od_tone, -12);
    lv_obj_set_align(ui_img_od_tone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_od_tone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_od_tone = lv_arc_create(ui_pnl_od_tone);
    lv_obj_set_width(ui_arc_od_tone, 95);
    lv_obj_set_height(ui_arc_od_tone, 97);
    lv_obj_set_x(ui_arc_od_tone, 0);
    lv_obj_set_y(ui_arc_od_tone, -12);
    lv_obj_set_align(ui_arc_od_tone, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_od_tone, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_od_tone, 0, 100);
    lv_arc_set_value(ui_arc_od_tone, 50);
    lv_arc_set_bg_angles(ui_arc_od_tone, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_od_tone, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_od_tone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_od_tone, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_od_tone, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_od_tone, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_od_tone, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_od_tone, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_od_tone, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_od_tone, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_od_tone = lv_label_create(ui_pnl_od_tone);
    lv_obj_set_width(ui_lbl_od_tone, 100);
    lv_obj_set_height(ui_lbl_od_tone, 17);
    lv_obj_set_align(ui_lbl_od_tone, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_od_tone, "TONE");
    lv_obj_set_style_text_color(ui_lbl_od_tone, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_od_tone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_od_tone, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_od_tone, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_od_gain = lv_obj_create(ui_pnl_od_controls);
    lv_obj_set_width(ui_pnl_od_gain, lv_pct(33));
    lv_obj_set_height(ui_pnl_od_gain, lv_pct(100));
    lv_obj_set_align(ui_pnl_od_gain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_od_gain, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                     LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_od_gain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_od_gain = lv_img_create(ui_pnl_od_gain);
    lv_img_set_src(ui_img_od_gain, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_od_gain, 104);
    lv_obj_set_height(ui_img_od_gain, 105);
    lv_obj_set_x(ui_img_od_gain, 0);
    lv_obj_set_y(ui_img_od_gain, -12);
    lv_obj_set_align(ui_img_od_gain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_od_gain, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_od_gain = lv_arc_create(ui_pnl_od_gain);
    lv_obj_set_width(ui_arc_od_gain, 95);
    lv_obj_set_height(ui_arc_od_gain, 97);
    lv_obj_set_x(ui_arc_od_gain, 0);
    lv_obj_set_y(ui_arc_od_gain, -12);
    lv_obj_set_align(ui_arc_od_gain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_od_gain, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_od_gain, 0, 100);
    lv_arc_set_value(ui_arc_od_gain, 40);
    lv_arc_set_bg_angles(ui_arc_od_gain, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_od_gain, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_od_gain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_od_gain, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_od_gain, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_od_gain, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_od_gain, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_od_gain, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_od_gain, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_od_gain, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_od_gain = lv_label_create(ui_pnl_od_gain);
    lv_obj_set_width(ui_lbl_od_gain, 68);
    lv_obj_set_height(ui_lbl_od_gain, 17);
    lv_obj_set_align(ui_lbl_od_gain, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_od_gain, "GAIN");
    lv_obj_set_style_text_color(ui_lbl_od_gain, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_od_gain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_od_gain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_od_gain, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_od_mode = lv_obj_create(ui_fx_overdrive);
    lv_obj_set_width(ui_pnl_od_mode, lv_pct(36));
    lv_obj_set_height(ui_pnl_od_mode, lv_pct(14));
    lv_obj_set_x(ui_pnl_od_mode, 0);
    lv_obj_set_y(ui_pnl_od_mode, 100);
    lv_obj_set_align(ui_pnl_od_mode, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_od_mode, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                     LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_od_mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_od_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_od_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_od_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_od_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_od_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_od_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sw_od_mode = lv_switch_create(ui_pnl_od_mode);
    lv_obj_set_width(ui_sw_od_mode, 50);
    lv_obj_set_height(ui_sw_od_mode, 25);
    lv_obj_set_align(ui_sw_od_mode, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_sw_od_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_od_mode, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sw_od_mode, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sw_od_mode, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_sw_od_mode, lv_color_hex(0x4C4E5B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_od_mode, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_od_mode_overdrive = lv_label_create(ui_pnl_od_mode);
    lv_obj_set_width(ui_lbl_od_mode_overdrive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_od_mode_overdrive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_od_mode_overdrive, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbl_od_mode_overdrive, "SOFT");
    lv_obj_set_style_text_color(ui_lbl_od_mode_overdrive, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_od_mode_overdrive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_od_mode_overdrive, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_od_mode_overdrive, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_od_mode_overdrive, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_od_mode_overdrive, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_add_state(ui_lbl_od_mode_overdrive, LV_STATE_CHECKED);

    ui_lbl_od_mode_distortion = lv_label_create(ui_pnl_od_mode);
    lv_obj_set_width(ui_lbl_od_mode_distortion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_od_mode_distortion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_od_mode_distortion, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbl_od_mode_distortion, "HARD");
    lv_obj_set_style_text_color(ui_lbl_od_mode_distortion, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_od_mode_distortion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_od_mode_distortion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_od_mode_distortion, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_od_mode_distortion, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_od_mode_distortion, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_btn_od_bypass, ui_event_btn_overdrive_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_od_mix, ui_event_arc_overdrive_mix, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_od_gain, ui_event_arc_overdrive_gain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_od_tone, ui_event_arc_overdrive_tone, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sw_od_mode, ui_event_sw_overdrive_mode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_overdrive, ui_event_fx_overdrive, LV_EVENT_ALL, NULL);

}
