// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_tremolo_screen_init(void)
{
    ui_fx_tremolo = lv_obj_create(NULL);

    ui_pnl_trem_content = lv_obj_create(ui_fx_tremolo);
    lv_obj_set_width(ui_pnl_trem_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_trem_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_trem_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_trem_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_trem_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_trem_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_trem_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_trem_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_trem_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_trem_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_trem_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_trem_fx_name = lv_label_create(ui_pnl_trem_content);
    lv_obj_set_width(ui_lbl_trem_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_trem_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_trem_fx_name, 0);
    lv_obj_set_y(ui_lbl_trem_fx_name, 10);
    lv_obj_set_align(ui_lbl_trem_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_trem_fx_name, "TREMOLO");
    lv_obj_set_style_text_color(ui_lbl_trem_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_trem_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_trem_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_trem_bypass = lv_imgbtn_create(ui_pnl_trem_content);
    lv_imgbtn_set_src(ui_btn_trem_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_trem_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_trem_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_trem_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_trem_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_trem_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_trem_bypass, 70);
    lv_obj_set_width(ui_btn_trem_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_trem_bypass, 15);
    lv_obj_set_y(ui_btn_trem_bypass, 0);
    lv_obj_set_align(ui_btn_trem_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_trem_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_trem_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_trem_bypass = lv_label_create(ui_btn_trem_bypass);
    lv_obj_set_width(ui_lbl_btn_trem_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_trem_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_trem_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_trem_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_trem_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_trem_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_trem_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_trem_controls = lv_obj_create(ui_pnl_trem_content);
    lv_obj_set_width(ui_pnl_trem_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_trem_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_trem_controls, 0);
    lv_obj_set_y(ui_pnl_trem_controls, 35);
    lv_obj_set_align(ui_pnl_trem_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_trem_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_trem_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_trem_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_trem_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_trem_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_trem_rate = lv_obj_create(ui_pnl_trem_controls);
    lv_obj_set_width(ui_pnl_trem_rate, lv_pct(33));
    lv_obj_set_height(ui_pnl_trem_rate, lv_pct(100));
    lv_obj_set_align(ui_pnl_trem_rate, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pnl_trem_rate, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_trem_rate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_trem_rate = lv_img_create(ui_pnl_trem_rate);
    lv_img_set_src(ui_img_trem_rate, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_trem_rate, 104);
    lv_obj_set_height(ui_img_trem_rate, 105);
    lv_obj_set_x(ui_img_trem_rate, 0);
    lv_obj_set_y(ui_img_trem_rate, -12);
    lv_obj_set_align(ui_img_trem_rate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_trem_rate, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_trem_rate = lv_arc_create(ui_pnl_trem_rate);
    lv_obj_set_width(ui_arc_trem_rate, 95);
    lv_obj_set_height(ui_arc_trem_rate, 97);
    lv_obj_set_x(ui_arc_trem_rate, 0);
    lv_obj_set_y(ui_arc_trem_rate, -12);
    lv_obj_set_align(ui_arc_trem_rate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_trem_rate, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_trem_rate, 1, 20);
    lv_arc_set_value(ui_arc_trem_rate, 8);
    lv_arc_set_bg_angles(ui_arc_trem_rate, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_trem_rate, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_trem_rate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_trem_rate, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_trem_rate, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_trem_rate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_trem_rate, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_trem_rate, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_trem_rate, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_trem_rate, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_trem_rate = lv_label_create(ui_pnl_trem_rate);
    lv_obj_set_width(ui_lbl_trem_rate, 68);
    lv_obj_set_height(ui_lbl_trem_rate, 17);
    lv_obj_set_align(ui_lbl_trem_rate, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_trem_rate, "RATE");
    lv_obj_set_style_text_color(ui_lbl_trem_rate, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_trem_rate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_trem_rate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_trem_rate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_trem_depth = lv_obj_create(ui_pnl_trem_controls);
    lv_obj_set_width(ui_pnl_trem_depth, lv_pct(33));
    lv_obj_set_height(ui_pnl_trem_depth, lv_pct(100));
    lv_obj_set_align(ui_pnl_trem_depth, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pnl_trem_depth,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_trem_depth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_trem_depth = lv_img_create(ui_pnl_trem_depth);
    lv_img_set_src(ui_img_trem_depth, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_img_trem_depth, 104);
    lv_obj_set_height(ui_img_trem_depth, 105);
    lv_obj_set_x(ui_img_trem_depth, 0);
    lv_obj_set_y(ui_img_trem_depth, -12);
    lv_obj_set_align(ui_img_trem_depth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_trem_depth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_arc_trem_depth = lv_arc_create(ui_pnl_trem_depth);
    lv_obj_set_width(ui_arc_trem_depth, 95);
    lv_obj_set_height(ui_arc_trem_depth, 97);
    lv_obj_set_x(ui_arc_trem_depth, 0);
    lv_obj_set_y(ui_arc_trem_depth, -12);
    lv_obj_set_align(ui_arc_trem_depth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arc_trem_depth, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_arc_trem_depth, 0, 50);
    lv_arc_set_value(ui_arc_trem_depth, 30);
    lv_arc_set_bg_angles(ui_arc_trem_depth, 129, 51);
    lv_obj_set_style_pad_left(ui_arc_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arc_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arc_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arc_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_trem_depth, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_trem_depth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_trem_depth, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arc_trem_depth, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arc_trem_depth, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_trem_depth, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_trem_depth, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arc_trem_depth, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_trem_depth, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_trem_depth = lv_label_create(ui_pnl_trem_depth);
    lv_obj_set_width(ui_lbl_trem_depth, 68);
    lv_obj_set_height(ui_lbl_trem_depth, 17);
    lv_obj_set_align(ui_lbl_trem_depth, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_trem_depth, "DEPTH");
    lv_obj_set_style_text_color(ui_lbl_trem_depth, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_trem_depth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_trem_depth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_trem_depth, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_trem_shape = lv_obj_create(ui_pnl_trem_controls);
    lv_obj_set_width(ui_pnl_trem_shape, lv_pct(33));
    lv_obj_set_height(ui_pnl_trem_shape, lv_pct(100));
    lv_obj_set_align(ui_pnl_trem_shape, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnl_trem_shape,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_pnl_trem_shape, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_trem_shape, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_trem_shape, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_trem_shape, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_trem_shape, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_trem_shape, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_trem_shape, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_trem_shape = lv_label_create(ui_pnl_trem_shape);
    lv_obj_set_width(ui_lbl_trem_shape, 68);
    lv_obj_set_height(ui_lbl_trem_shape, 17);
    lv_obj_set_align(ui_lbl_trem_shape, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_trem_shape, "SHAPE");
    lv_obj_set_style_text_color(ui_lbl_trem_shape, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_trem_shape, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_trem_shape, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_trem_shape, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sw_trem_shape = lv_switch_create(ui_pnl_trem_shape);
    lv_obj_set_width(ui_sw_trem_shape, 50);
    lv_obj_set_height(ui_sw_trem_shape, 25);
    lv_obj_set_x(ui_sw_trem_shape, 0);
    lv_obj_set_y(ui_sw_trem_shape, -10);
    lv_obj_set_align(ui_sw_trem_shape, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_sw_trem_shape, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_trem_shape, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sw_trem_shape, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sw_trem_shape, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_sw_trem_shape, lv_color_hex(0x4C4E5B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sw_trem_shape, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_trem_square = lv_label_create(ui_pnl_trem_shape);
    lv_obj_set_width(ui_lbl_trem_square, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_trem_square, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_trem_square, 0);
    lv_obj_set_y(ui_lbl_trem_square, -10);
    lv_obj_set_align(ui_lbl_trem_square, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbl_trem_square, "SQ ");
    lv_obj_set_style_text_color(ui_lbl_trem_square, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_trem_square, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_trem_square, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_trem_square, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_trem_square, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_trem_square, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_add_state(ui_lbl_trem_square, LV_STATE_CHECKED);

    ui_lbl_trem_sine = lv_label_create(ui_pnl_trem_shape);
    lv_obj_set_width(ui_lbl_trem_sine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_trem_sine, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_trem_sine, 0);
    lv_obj_set_y(ui_lbl_trem_sine, -10);
    lv_obj_set_align(ui_lbl_trem_sine, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbl_trem_sine, "SIN");
    lv_obj_set_style_text_color(ui_lbl_trem_sine, lv_color_hex(0x9395A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_trem_sine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_trem_sine, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_trem_sine, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lbl_trem_sine, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lbl_trem_sine, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_btn_trem_bypass, ui_event_btn_trem_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_trem_rate, ui_event_arc_trem_rate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arc_trem_depth, ui_event_arc_trem_depth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sw_trem_shape, ui_event_sw_tremolo_shape, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_tremolo, ui_event_fx_tremolo, LV_EVENT_ALL, NULL);

}
