// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_fx_tuner_screen_init(void)
{
    ui_fx_tuner = lv_obj_create(NULL);

    ui_pnl_tuner_content = lv_obj_create(ui_fx_tuner);
    lv_obj_set_width(ui_pnl_tuner_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_tuner_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_tuner_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_tuner_content, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_tuner_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_tuner_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_tuner_fx_name = lv_label_create(ui_pnl_tuner_content);
    lv_obj_set_width(ui_lbl_tuner_fx_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_fx_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_tuner_fx_name, 0);
    lv_obj_set_y(ui_lbl_tuner_fx_name, 10);
    lv_obj_set_align(ui_lbl_tuner_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_tuner_fx_name, "CHROMATIC TUNER");
    lv_obj_set_style_text_color(ui_lbl_tuner_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_fx_name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_tuner_bypass = lv_imgbtn_create(ui_pnl_tuner_content);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_imgbtn_set_src(ui_btn_tuner_bypass, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_obj_set_height(ui_btn_tuner_bypass, 70);
    lv_obj_set_width(ui_btn_tuner_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_tuner_bypass, 15);
    lv_obj_set_y(ui_btn_tuner_bypass, 0);
    lv_obj_set_align(ui_btn_tuner_bypass, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_tuner_bypass, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_btn_tuner_bypass, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_lbl_btn_tuner_bypass = lv_label_create(ui_btn_tuner_bypass);
    lv_obj_set_width(ui_lbl_btn_tuner_bypass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_btn_tuner_bypass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_btn_tuner_bypass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_tuner_bypass, "ON");
    lv_obj_set_style_text_color(ui_lbl_btn_tuner_bypass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_btn_tuner_bypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_btn_tuner_bypass, &ui_font_14_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_tuner_controls = lv_obj_create(ui_pnl_tuner_content);
    lv_obj_set_width(ui_pnl_tuner_controls, lv_pct(90));
    lv_obj_set_height(ui_pnl_tuner_controls, lv_pct(60));
    lv_obj_set_x(ui_pnl_tuner_controls, 0);
    lv_obj_set_y(ui_pnl_tuner_controls, 35);
    lv_obj_set_align(ui_pnl_tuner_controls, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pnl_tuner_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_tuner_controls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_tuner_controls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnl_tuner_controls, lv_color_hex(0x747682), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnl_tuner_controls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* TODO: This widget consumes a lot of CPU, optimize or replace it */
    ui_meter_tuner_cents = lv_meter_create(ui_pnl_tuner_controls);
    lv_obj_align(ui_meter_tuner_cents, LV_ALIGN_TOP_MID, 0, 0);
    lv_obj_set_size(ui_meter_tuner_cents, 200, 200);
    
    lv_meter_scale_t * scale = lv_meter_add_scale(ui_meter_tuner_cents);
    lv_meter_set_scale_ticks(ui_meter_tuner_cents, scale, 21, 2, 10, lv_palette_main(LV_PALETTE_GREY));
    lv_meter_set_scale_major_ticks(ui_meter_tuner_cents, scale, 5, 4, 15, lv_palette_main(LV_PALETTE_GREY), 15);
    lv_meter_set_scale_range(ui_meter_tuner_cents, scale, -50, 50, 120, 210);
    
    /* Set [-5, +5] range as green */
    lv_meter_indicator_t * indic;
    indic = lv_meter_add_arc(ui_meter_tuner_cents, scale, 2, lv_palette_main(LV_PALETTE_GREY), 0);
    lv_meter_set_indicator_start_value(ui_meter_tuner_cents, indic, -50);
    lv_meter_set_indicator_end_value(ui_meter_tuner_cents, indic, 50);

    indic = lv_meter_add_arc(ui_meter_tuner_cents, scale, 2, lv_color_hex(UI_PALETTE_SPRING_GREEN), 0);
    lv_meter_set_indicator_start_value(ui_meter_tuner_cents, indic, -5);
    lv_meter_set_indicator_end_value(ui_meter_tuner_cents, indic, 5);

    indic = lv_meter_add_scale_lines(ui_meter_tuner_cents, scale, lv_color_hex(UI_PALETTE_SPRING_GREEN), lv_color_hex(UI_PALETTE_SPRING_GREEN), false, 0);
    lv_meter_set_indicator_start_value(ui_meter_tuner_cents, indic, -5);
    lv_meter_set_indicator_end_value(ui_meter_tuner_cents, indic, 5);

    /* Create needle */
    ui_meter_tuner_cents_indic = lv_meter_add_needle_line(ui_meter_tuner_cents, scale, 2, lv_color_hex(UI_PALETTE_SPRING_GREEN), -10);

    ui_lbl_tuner_pitch = lv_label_create(ui_pnl_tuner_controls);
    lv_obj_set_width(ui_lbl_tuner_pitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_pitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(ui_lbl_tuner_pitch, LV_ALIGN_TOP_LEFT, 0, 0);
    lv_label_set_text(ui_lbl_tuner_pitch, "---.-Hz");
    lv_obj_set_style_text_color(ui_lbl_tuner_pitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_pitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_pitch, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_tuner_note = lv_label_create(ui_pnl_tuner_controls);
    lv_obj_set_width(ui_lbl_tuner_note, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_note, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(ui_lbl_tuner_note, LV_ALIGN_TOP_LEFT, 0, 25);
    lv_label_set_text(ui_lbl_tuner_note, "---");
    lv_obj_set_style_text_color(ui_lbl_tuner_note, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_note, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_note, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_tuner_cents = lv_label_create(ui_pnl_tuner_controls);
    lv_obj_set_width(ui_lbl_tuner_cents, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_tuner_cents, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(ui_lbl_tuner_cents, LV_ALIGN_TOP_RIGHT, 0, 0);
    lv_label_set_text(ui_lbl_tuner_cents, "--c");
    lv_obj_set_style_text_color(ui_lbl_tuner_cents, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_tuner_cents, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_tuner_cents, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_tuner_bypass, ui_event_btn_tuner_bypass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fx_tuner, ui_event_fx_tuner, LV_EVENT_ALL, NULL);

}
