// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_splash_screen_init(void)
{
    ui_splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_splash, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo_gmfx = lv_img_create(ui_splash);
    lv_img_set_src(ui_logo_gmfx, &ui_img_logo_gmfx);
    lv_obj_set_width(ui_logo_gmfx, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_logo_gmfx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_logo_gmfx, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_gmfx, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_logo_gmfx, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_opa(ui_logo_gmfx, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_logo_gmfx, LV_OPA_100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_logo_gmfx, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_splash, ui_event_splash, LV_EVENT_ALL, NULL);
}
