// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);

    ui_pnl_sett_content = lv_obj_create(ui_settings);
    lv_obj_set_width(ui_pnl_sett_content, lv_pct(100));
    lv_obj_set_height(ui_pnl_sett_content, lv_pct(100));
    lv_obj_clear_flag(ui_pnl_sett_content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnl_sett_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnl_sett_content, lv_color_hex(0x25272E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_sett_content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_sett_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pnl_sett_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pnl_sett_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pnl_sett_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pnl_sett_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_sett_name = lv_label_create(ui_pnl_sett_content);
    lv_obj_set_width(ui_lbl_sett_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_sett_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_sett_name, 0);
    lv_obj_set_y(ui_lbl_sett_name, 10);
    lv_obj_set_align(ui_lbl_sett_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_sett_name, "SETTINGS");
    lv_obj_set_style_text_color(ui_lbl_sett_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_sett_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_sett_name, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_in_vol = lv_obj_create(ui_pnl_sett_content);
    lv_obj_set_width(ui_pnl_in_vol, 50);
    lv_obj_set_height(ui_pnl_in_vol, lv_pct(100));
    lv_obj_set_x(ui_pnl_in_vol, 10);
    lv_obj_set_y(ui_pnl_in_vol, 0);
    lv_obj_set_align(ui_pnl_in_vol, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pnl_in_vol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_in_vol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_in_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_in_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sld_in_vol = lv_slider_create(ui_pnl_in_vol);
    lv_slider_set_range(ui_sld_in_vol, 0, 31);
    lv_slider_set_value(ui_sld_in_vol, 11, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sld_in_vol) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sld_in_vol, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sld_in_vol, 40);
    lv_obj_set_height(ui_sld_in_vol, 180);
    lv_obj_set_align(ui_sld_in_vol, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sld_in_vol, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sld_in_vol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sld_in_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sld_in_vol, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_sld_in_vol, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sld_in_vol, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sld_in_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sld_in_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sld_in_vol, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sld_in_vol, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_sld_in_vol, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_sld_in_vol, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_sld_in_vol, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_sld_in_vol, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sld_in_vol, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sld_in_vol, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sld_in_vol, &ui_img_pot_ver_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_in_vol_dbmax = lv_label_create(ui_pnl_in_vol);
    lv_obj_set_width(ui_lbl_in_vol_dbmax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_in_vol_dbmax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_in_vol_dbmax, 0);
    lv_obj_set_y(ui_lbl_in_vol_dbmax, -10);
    lv_obj_set_align(ui_lbl_in_vol_dbmax, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_in_vol_dbmax, "30 dB");
    lv_obj_set_style_text_color(ui_lbl_in_vol_dbmax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_in_vol_dbmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_in_vol_dbmax, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_in_vol = lv_label_create(ui_pnl_in_vol);
    lv_obj_set_width(ui_lbl_in_vol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_in_vol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_in_vol, 0);
    lv_obj_set_y(ui_lbl_in_vol, 10);
    lv_obj_set_align(ui_lbl_in_vol, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_in_vol, "IN");
    lv_obj_set_style_text_color(ui_lbl_in_vol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_in_vol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_in_vol, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnl_out_vol = lv_obj_create(ui_pnl_sett_content);
    lv_obj_set_width(ui_pnl_out_vol, 50);
    lv_obj_set_height(ui_pnl_out_vol, lv_pct(100));
    lv_obj_set_x(ui_pnl_out_vol, -10);
    lv_obj_set_y(ui_pnl_out_vol, 0);
    lv_obj_set_align(ui_pnl_out_vol, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pnl_out_vol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnl_out_vol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnl_out_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnl_out_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sld_out_vol = lv_slider_create(ui_pnl_out_vol);
    lv_slider_set_range(ui_sld_out_vol, 0, 63);
    lv_slider_set_value(ui_sld_out_vol, 57, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sld_out_vol) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sld_out_vol, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sld_out_vol, 40);
    lv_obj_set_height(ui_sld_out_vol, 180);
    lv_obj_set_align(ui_sld_out_vol, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sld_out_vol, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sld_out_vol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sld_out_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sld_out_vol, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_sld_out_vol, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sld_out_vol, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sld_out_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sld_out_vol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sld_out_vol, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sld_out_vol, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_sld_out_vol, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_sld_out_vol, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_sld_out_vol, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_sld_out_vol, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sld_out_vol, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sld_out_vol, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sld_out_vol, &ui_img_pot_ver_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_out_vol_dbmax = lv_label_create(ui_pnl_out_vol);
    lv_obj_set_width(ui_lbl_out_vol_dbmax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_out_vol_dbmax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_out_vol_dbmax, 0);
    lv_obj_set_y(ui_lbl_out_vol_dbmax, -10);
    lv_obj_set_align(ui_lbl_out_vol_dbmax, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbl_out_vol_dbmax, "6 dB");
    lv_obj_set_style_text_color(ui_lbl_out_vol_dbmax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_out_vol_dbmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_out_vol_dbmax, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_out_vol = lv_label_create(ui_pnl_out_vol);
    lv_obj_set_width(ui_lbl_out_vol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_out_vol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_out_vol, 0);
    lv_obj_set_y(ui_lbl_out_vol, 10);
    lv_obj_set_align(ui_lbl_out_vol, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl_out_vol, "OUT");
    lv_obj_set_style_text_color(ui_lbl_out_vol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_out_vol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_out_vol, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cb_some_setting = lv_checkbox_create(ui_pnl_sett_content);
    lv_checkbox_set_text(ui_cb_some_setting, "MUTE");
    lv_obj_set_width(ui_cb_some_setting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cb_some_setting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cb_some_setting, 0);
    lv_obj_set_y(ui_cb_some_setting, 50);
    lv_obj_set_align(ui_cb_some_setting, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_cb_some_setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_cb_some_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cb_some_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cb_some_setting, lv_color_hex(0x25272E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cb_some_setting, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cb_some_setting, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cb_some_setting, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cb_some_setting, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cb_some_setting, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_cb_some_setting, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_sld_in_vol, ui_event_sld_in_vol, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sld_out_vol, ui_event_sld_out_vol, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cb_some_setting, ui_event_cb_some_setting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);

}
