// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#ifndef GIT_REVISION
#define GIT_REVISION "unknown"
#endif

//-----------------------------------------------------------------------------
/* private */

static const char * msgbox_btns[] = {"Yes", "No", ""};
static const uint16_t msgbox_yes_btn_idx = 0;

//-----------------------------------------------------------------------------
/* menu handlers */

static void menu_exit_handler(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    lv_obj_t * menu = lv_event_get_user_data(e);

    if (lv_menu_back_btn_is_root(menu, obj))
        _ui_screen_change(&ui_settings_parent_screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, NULL);
}

static void menu_style_changed_handler(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);

    lv_obj_set_style_bg_color(obj, lv_obj_get_style_bg_color(ui_settings, 0), 0);
}

static lv_obj_t * menu_create_text(lv_obj_t * parent, const char * icon, const char * txt)
{
    lv_obj_t * obj = lv_menu_cont_create(parent);

    lv_obj_t * img = NULL;
    lv_obj_t * label = NULL;

    if (icon)
    {
        img = lv_img_create(obj);
        lv_img_set_src(img, icon);
    }

    if (txt)
    {
        label = lv_label_create(obj);
        lv_label_set_text(label, txt);
        lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_set_flex_grow(label, 1);
    }

    lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(obj, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

    return obj;
}

static lv_obj_t * menu_create_slider(lv_obj_t * parent, const char * icon, const char * txt, int32_t min, int32_t max, int32_t val, lv_event_cb_t event_cb)
{
    lv_obj_t * obj = menu_create_text(parent, icon, txt);

    lv_obj_t * slider = lv_slider_create(obj);
    lv_obj_set_flex_grow(slider, 1);
    lv_slider_set_range(slider, min, max);
    lv_slider_set_value(slider, val, LV_ANIM_OFF);

    if (icon == NULL)
        lv_obj_add_flag(slider, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);

    if (event_cb)
        lv_obj_add_event_cb(slider, event_cb, LV_EVENT_ALL, NULL);

    return obj;
}

static lv_obj_t * menu_create_switch(lv_obj_t * parent, const char * icon, const char * txt, bool chk, lv_event_cb_t event_cb)
{
    lv_obj_t * obj = menu_create_text(parent, icon, txt);

    lv_obj_t * sw = lv_switch_create(obj);
    lv_obj_add_state(sw, chk ? LV_STATE_CHECKED : 0);

    if (event_cb)
        lv_obj_add_event_cb(sw, event_cb, LV_EVENT_ALL, NULL);

    return obj;
}

static void list_btn_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    lv_obj_t ** selected_btn = (lv_obj_t **)e->user_data;

    if (code == LV_EVENT_CLICKED)
    {
        (*selected_btn) = ((*selected_btn) == obj) ? NULL : obj;

        lv_obj_t * parent = lv_obj_get_parent(obj);
        for (unsigned i = 0; i < lv_obj_get_child_cnt(parent); i++)
        {
            lv_obj_t * child = lv_obj_get_child(parent, i);

            if (child == (*selected_btn))
                lv_obj_clear_state(child, LV_STATE_CHECKED);
            else
                lv_obj_add_state(child, LV_STATE_CHECKED);
        }
    }
}

static void list_add_btn(lv_obj_t * list, const char * text, lv_obj_t ** selected_btn)
{
    uint32_t index = lv_obj_get_child_cnt(list);

    lv_obj_t * btn = lv_btn_create(list);
    lv_obj_set_width(btn, LV_SIZE_CONTENT);
    lv_obj_set_style_text_color(btn, lv_color_black(), LV_STATE_DEFAULT);
    lv_obj_add_event_cb(btn, list_btn_handler, LV_EVENT_CLICKED, selected_btn);
    lv_obj_add_state(btn, LV_STATE_CHECKED);
    lv_obj_move_to_index(btn, index);
    lv_obj_scroll_to_view(btn, LV_ANIM_ON);

    lv_obj_t * lab = lv_label_create(btn);
    lv_label_set_text(lab, text);
}

//-----------------------------------------------------------------------------
/* effects handlers */

static bool is_fx_name_in_chain(const char *name)
{
    for (unsigned i = 0; i < lv_obj_get_child_cnt(ui_list_sett_fx_chain); i++)
    {
        lv_obj_t * btn = lv_obj_get_child(ui_list_sett_fx_chain, i);
        if (strcmp(name, lv_list_get_btn_text(ui_list_sett_fx_chain, btn)) == 0)
            return true;
    }

    return false;
}

static int fx_name_to_id(const char *name)
{
    for (unsigned i = 0; i < ui_fx_names_size; i++)
    {
        if (strcmp(ui_fx_names[i], name) == 0)
            return i;
    }

    return -1;
}

static void fx_ops_back_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_CLICKED)
    {
        lv_obj_clear_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_HIDDEN);
        lv_obj_del(ui_list_sett_fx_items);
    }
}

static void fx_ops_add_fx_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * fx_item = lv_event_get_target(e);

    if (code == LV_EVENT_CLICKED)
    {
        list_add_btn(ui_list_sett_fx_chain, lv_list_get_btn_text(ui_list_sett_fx_items, fx_item), &ui_btn_sett_curr_fx);

        ui_settings_add_effect(lv_obj_get_index(fx_item) - 1);

        lv_obj_clear_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_HIDDEN);
        lv_obj_del(ui_list_sett_fx_items);
    }
}

static void fx_ops_add_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_CLICKED)
    {
        /* Create list of available effects to add to effects chain */
        ui_list_sett_fx_items = lv_list_create(lv_obj_get_parent(ui_list_sett_fx_ops));
        lv_obj_add_flag(ui_list_sett_fx_items, LV_OBJ_FLAG_IGNORE_LAYOUT);
        lv_obj_set_size(ui_list_sett_fx_items, lv_pct(40), lv_pct(100));
        lv_obj_align(ui_list_sett_fx_items, LV_ALIGN_TOP_RIGHT, 0, 0);

        lv_obj_t * btn = lv_list_add_btn(ui_list_sett_fx_items, LV_SYMBOL_LEFT, NULL);
        lv_obj_add_event_cb(btn, fx_ops_back_handler, LV_EVENT_ALL, NULL);
        lv_group_remove_obj(btn);

        for (unsigned i = 0; i < ui_fx_names_size; i++)
        {
            btn = lv_list_add_btn(ui_list_sett_fx_items, NULL, ui_fx_names[i]);

            if (is_fx_name_in_chain(ui_fx_names[i]))
            {
                lv_obj_set_style_text_color(btn, lv_color_darken(lv_color_white(), 127), LV_STATE_DISABLED);
                lv_obj_add_state(btn, LV_STATE_DISABLED);
            }

            lv_obj_add_event_cb(btn, fx_ops_add_fx_handler, LV_EVENT_ALL, NULL);
            lv_group_remove_obj(btn);
        }

        lv_obj_add_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_HIDDEN);
    }
}

static void fx_ops_remove_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if ((code == LV_EVENT_CLICKED) || (code == LV_EVENT_LONG_PRESSED_REPEAT))
    {
        if (ui_btn_sett_curr_fx == NULL)
            return;

        int fx_id = fx_name_to_id(lv_list_get_btn_text(ui_list_sett_fx_chain, ui_btn_sett_curr_fx));
        if (fx_id >= 0)
            ui_settings_remove_effect(fx_id);

        uint32_t index = lv_obj_get_index(ui_btn_sett_curr_fx);
        if (index == lv_obj_get_child_cnt(ui_list_sett_fx_chain) - 1)
            index--;

        lv_obj_del(ui_btn_sett_curr_fx);
        ui_btn_sett_curr_fx = lv_obj_get_child(ui_list_sett_fx_chain, index);

        if (ui_btn_sett_curr_fx == NULL)
            return;

        lv_obj_clear_state(ui_btn_sett_curr_fx, LV_STATE_CHECKED);
        lv_obj_move_to_index(ui_btn_sett_curr_fx, index);
        lv_obj_scroll_to_view(ui_btn_sett_curr_fx, LV_ANIM_ON);
    }
}

static void fx_ops_move_up_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if ((code == LV_EVENT_CLICKED) || (code == LV_EVENT_LONG_PRESSED_REPEAT))
    {
        if (ui_btn_sett_curr_fx == NULL)
            return;

        const uint32_t index = lv_obj_get_index(ui_btn_sett_curr_fx);
        if (index <= 0)
            return;

        lv_obj_move_to_index(ui_btn_sett_curr_fx, index - 1);
        lv_obj_scroll_to_view(ui_btn_sett_curr_fx, LV_ANIM_ON);

        int fx_id = fx_name_to_id(lv_list_get_btn_text(ui_list_sett_fx_chain, ui_btn_sett_curr_fx));
        if (fx_id >= 0)
            ui_settings_move_effect(fx_id, -1);
    }
}

static void fx_ops_move_down_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if ((code == LV_EVENT_CLICKED) || (code == LV_EVENT_LONG_PRESSED_REPEAT))
    {
        if (ui_btn_sett_curr_fx == NULL)
            return;

        const uint32_t index = lv_obj_get_index(ui_btn_sett_curr_fx);
        lv_obj_move_to_index(ui_btn_sett_curr_fx, index + 1);
        lv_obj_scroll_to_view(ui_btn_sett_curr_fx, LV_ANIM_ON);

        int fx_id = fx_name_to_id(lv_list_get_btn_text(ui_list_sett_fx_chain, ui_btn_sett_curr_fx));
        if (fx_id >= 0)
            ui_settings_move_effect(fx_id, 1);
    }
}

static void create_effects_management_lists(lv_obj_t * parent)
{
    ui_btn_sett_curr_fx = NULL;

    /* Create a list of effects in chain */
    ui_list_sett_fx_chain = lv_list_create(parent);
    lv_obj_add_flag(ui_list_sett_fx_chain, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_set_style_pad_row(ui_list_sett_fx_chain, 5, 0);
    lv_obj_set_size(ui_list_sett_fx_chain, lv_pct(60-1), lv_pct(100));
    lv_obj_align(ui_list_sett_fx_chain, LV_ALIGN_TOP_LEFT, 0, 0);

    /* Create a second list with buttons for various operations on effects chain */
    ui_list_sett_fx_ops = lv_list_create(parent);
    lv_obj_add_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_set_size(ui_list_sett_fx_ops, lv_pct(40-1), LV_SIZE_CONTENT);
    lv_obj_align(ui_list_sett_fx_ops, LV_ALIGN_TOP_RIGHT, 0, 0);

    lv_obj_t * btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_PLUS, "Add...");
    lv_obj_add_event_cb(btn, fx_ops_add_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_TRASH, "Remove");
    lv_obj_add_event_cb(btn, fx_ops_remove_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_UP, "Move up");
    lv_obj_add_event_cb(btn, fx_ops_move_up_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_DOWN, "Move down");
    lv_obj_add_event_cb(btn, fx_ops_move_down_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);
}

//-----------------------------------------------------------------------------
/* presets handlers */

static void preset_ops_load_handler(lv_event_t * e)
{
    if (ui_btn_sett_curr_preset == NULL)
        return;

    const char * preset_name = lv_list_get_btn_text(ui_list_sett_avail_presets, ui_btn_sett_curr_preset);
    ui_settings_load_preset(preset_name);
}

static void msgbox_preset_overwrite_handler(lv_event_t * e)
{
    lv_obj_t *mbox = lv_event_get_current_target(e);

    uint16_t btn_idx = lv_msgbox_get_active_btn(mbox);

    if (btn_idx == msgbox_yes_btn_idx)
    {
        const char * preset_name = lv_list_get_btn_text(ui_list_sett_avail_presets, ui_btn_sett_curr_preset);
        ui_settings_save_preset(preset_name);
    }

    lv_msgbox_close(mbox);
}

static void textarea_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);

    if (code == LV_EVENT_READY)
    {
        /* Verify filename */
        const char * text = lv_textarea_get_text(ta);
        if (text && strlen(text) > 0 && strchr(text, '/') == NULL && strcmp(text, ".") != 0 && strcmp(text, "..") != 0)
        {
            if (ui_btn_sett_curr_preset)
            {
                /* Rename existing preset */
                const char * old_text = lv_list_get_btn_text(ui_list_sett_avail_presets, ui_btn_sett_curr_preset);
                ui_settings_rename_preset(old_text, text);
                lv_label_set_text(lv_obj_get_child(ui_btn_sett_curr_preset, -1), text);
            }
            else
            {
                /* Save new preset */
                ui_settings_save_preset(text);
                list_add_btn(ui_list_sett_avail_presets, text, &ui_btn_sett_curr_preset);
            }

            /* Delete dialog */
            lv_obj_del_async(lv_obj_get_parent(ta));
        }
    }
    else if (code == LV_EVENT_CANCEL)
    {
        /* Delete dialog */
        lv_obj_del_async(lv_obj_get_parent(ta));
    }
}

static void show_keyboard_with_textarea(const char * placeholder_txt, const char * initial_txt)
{
    /* Create dialog with background, keyboard and text area */
    lv_obj_t * bg;
    bg = lv_obj_create(lv_scr_act());
    lv_obj_remove_style_all(bg);
    lv_obj_set_size(bg, lv_pct(100), lv_pct(100));
    lv_obj_set_style_bg_color(bg, lv_palette_lighten(LV_PALETTE_GREY, 1), 0);
    lv_obj_set_style_bg_opa(bg, LV_OPA_40, 0);
    lv_obj_add_flag(bg, LV_OBJ_FLAG_CLICKABLE);

    lv_obj_t * kb = lv_keyboard_create(bg);
    lv_obj_t * ta = lv_textarea_create(bg);
    lv_textarea_set_one_line(ta, true);
    lv_textarea_set_max_length(ta, 32);
    lv_obj_align_to(ta, kb, LV_ALIGN_OUT_TOP_MID, 0, -5);
    lv_obj_add_event_cb(ta, textarea_event_cb, LV_EVENT_ALL, kb);
    lv_obj_add_state(ta, LV_STATE_FOCUSED);

    if (placeholder_txt)
        lv_textarea_set_placeholder_text(ta, placeholder_txt);

    if (initial_txt)
        lv_textarea_add_text(ta, initial_txt);

    lv_keyboard_set_textarea(kb, ta);
}

static void preset_ops_save_handler(lv_event_t * e)
{
    if (ui_btn_sett_curr_preset)
    {
        /* Show a messagebox to confirm overwriting */
        lv_obj_t * mbox = lv_msgbox_create(NULL, NULL, "Do you want to overwrite existing preset?", msgbox_btns, false);
        lv_obj_add_event_cb(mbox, msgbox_preset_overwrite_handler, LV_EVENT_VALUE_CHANGED, NULL);
        lv_obj_center(mbox);
    }
    else
    {
        /* Show a keyboard to enter new preset name */
        show_keyboard_with_textarea("Enter preset name", NULL);
    }
}

static void preset_ops_rename_handler(lv_event_t * e)
{
    if (ui_btn_sett_curr_preset == NULL)
        return;

    /* Show a keyboard to modify current preset name */
    const char * preset_name = lv_list_get_btn_text(ui_list_sett_avail_presets, ui_btn_sett_curr_preset);
    show_keyboard_with_textarea("Enter preset name", preset_name);
}

static void msgbox_preset_remove_handler(lv_event_t * e)
{
    lv_obj_t *mbox = lv_event_get_current_target(e);

    uint16_t btn_idx = lv_msgbox_get_active_btn(mbox);

    if (btn_idx == msgbox_yes_btn_idx)
    {
        const char * preset_name = lv_list_get_btn_text(ui_list_sett_avail_presets, ui_btn_sett_curr_preset);
        ui_settings_remove_preset(preset_name);
        lv_obj_del(ui_btn_sett_curr_preset);
        ui_btn_sett_curr_preset = NULL;
    }

    lv_msgbox_close(mbox);
}

static void preset_ops_remove_handler(lv_event_t * e)
{
    if (ui_btn_sett_curr_preset == NULL)
        return;

    /* Show a messagebox to confirm removal */
    lv_obj_t * mbox = lv_msgbox_create(NULL, NULL, "Do you want to remove preset?", msgbox_btns, false);
    lv_obj_add_event_cb(mbox, msgbox_preset_remove_handler, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_center(mbox);
}

static void create_presets_management_lists(lv_obj_t * parent)
{
    ui_btn_sett_curr_preset = NULL;

    /* Create a list of available presets */
    ui_list_sett_avail_presets = lv_list_create(parent);
    lv_obj_add_flag(ui_list_sett_avail_presets, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_set_style_pad_row(ui_list_sett_avail_presets, 5, 0);
    lv_obj_set_size(ui_list_sett_avail_presets, lv_pct(60-1), lv_pct(100));
    lv_obj_align(ui_list_sett_avail_presets, LV_ALIGN_TOP_LEFT, 0, 0);

    /* Create a second list with buttons for various operations on presets */
    ui_list_sett_presets_ops = lv_list_create(parent);
    lv_obj_add_flag(ui_list_sett_presets_ops, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_set_size(ui_list_sett_presets_ops, lv_pct(40-1), LV_SIZE_CONTENT);
    lv_obj_align(ui_list_sett_presets_ops, LV_ALIGN_TOP_RIGHT, 0, 0);

    lv_obj_t * btn = lv_list_add_btn(ui_list_sett_presets_ops, LV_SYMBOL_FILE, "Load");
    lv_obj_add_event_cb(btn, preset_ops_load_handler, LV_EVENT_CLICKED, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_presets_ops, LV_SYMBOL_SAVE, "Save");
    lv_obj_add_event_cb(btn, preset_ops_save_handler, LV_EVENT_CLICKED, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_presets_ops, LV_SYMBOL_EDIT, "Rename");
    lv_obj_add_event_cb(btn, preset_ops_rename_handler, LV_EVENT_CLICKED, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_presets_ops, LV_SYMBOL_TRASH, "Remove");
    lv_obj_add_event_cb(btn, preset_ops_remove_handler, LV_EVENT_CLICKED, NULL);
    lv_group_remove_obj(btn);
}

//-----------------------------------------------------------------------------
/* factory reset handlers */

static void msgbox_factory_reset_handler(lv_event_t * e)
{
    lv_obj_t *mbox = lv_event_get_current_target(e);

    uint16_t btn_idx = lv_msgbox_get_active_btn(mbox);

    if (btn_idx == msgbox_yes_btn_idx)
        ui_settings_factory_reset();

    lv_msgbox_close(mbox);
}

static void menu_factory_reset_handler(lv_event_t * e)
{
    lv_obj_t * mbox = lv_msgbox_create(NULL, NULL, "Do you want to reset device to a factory state?", msgbox_btns, false);
    lv_obj_add_event_cb(mbox, msgbox_factory_reset_handler, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_center(mbox);
}

//-----------------------------------------------------------------------------
/* public */

void ui_settings_clear_effects_list(void)
{
    uint32_t index = lv_obj_get_child_cnt(ui_list_sett_fx_chain);

    while (index--)
    {
        lv_obj_t * fx = lv_obj_get_child(ui_list_sett_fx_chain, index);
        lv_obj_del(fx);
    }

    ui_btn_sett_curr_fx = NULL;
}

void ui_settings_clear_presets_list(void)
{
    uint32_t index = lv_obj_get_child_cnt(ui_list_sett_avail_presets);

    while (index--)
    {
        lv_obj_t * fx = lv_obj_get_child(ui_list_sett_avail_presets, index);
        lv_obj_del(fx);
    }

    ui_btn_sett_curr_preset = NULL;
}

void ui_settings_update_presets_list(const char * preset_name)
{
    list_add_btn(ui_list_sett_avail_presets, preset_name, &ui_btn_sett_curr_preset);
}

void ui_settings_update_effects_list(uint8_t effect_id)
{
    list_add_btn(ui_list_sett_fx_chain, ui_fx_names[effect_id], &ui_btn_sett_curr_fx);
}

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);

    /* Create menu */
    lv_obj_t * menu = lv_menu_create(ui_settings);
    ui_menu_sett = menu;

    lv_obj_set_style_bg_color(menu, lv_obj_get_style_bg_color(ui_settings, 0), 0);
    lv_menu_set_mode_root_back_btn(menu, LV_MENU_ROOT_BACK_BTN_ENABLED);
    lv_obj_add_event_cb(menu, menu_style_changed_handler, LV_EVENT_STYLE_CHANGED, NULL);
    lv_obj_add_event_cb(menu, menu_exit_handler, LV_EVENT_CLICKED, menu);
    lv_obj_set_size(menu, lv_pct(100), lv_pct(100));
    lv_obj_center(menu);

    /* Modify the back button */
    const lv_coord_t menu_pad_hor = lv_obj_get_style_pad_left(lv_menu_get_main_header(menu),0);
    lv_obj_t * back_btn = lv_menu_get_main_header_back_btn(menu);
    lv_obj_set_style_pad_hor(back_btn, menu_pad_hor, 0);

    lv_obj_t * cont;
    lv_obj_t * section;

    /* Create sub pages */
    lv_obj_t * sub_audio_page = lv_menu_page_create(menu, "Audio");
    lv_obj_set_style_pad_hor(sub_audio_page, menu_pad_hor, 0);
    lv_menu_separator_create(sub_audio_page);
    section = lv_menu_section_create(sub_audio_page);
    cont = menu_create_slider(section, NULL, "MAIN input volume", 0, 31, 11, ui_event_sld_in_vol);
    ui_sld_sett_main_in_vol = lv_obj_get_child(cont, -1);
    cont = menu_create_slider(section, NULL, "AUX input volume", 0, 31, 11, ui_event_sld_in_vol);
    ui_sld_sett_aux_in_vol = lv_obj_get_child(cont, -1);
    cont = menu_create_switch(section, NULL, "Route onboard microphone to AUX", false, ui_event_sw_route_mic_to_aux);
    ui_sw_sett_route_mic_to_aux = lv_obj_get_child(cont, -1);
    lv_menu_separator_create(sub_audio_page);
    section = lv_menu_section_create(sub_audio_page);
    cont = menu_create_slider(section, NULL, "OUT volume", 0, 63, 57, ui_event_sld_out_vol);
    ui_sld_sett_out_vol = lv_obj_get_child(cont, -1);
    cont = menu_create_switch(section, NULL, "Mute output", false, ui_event_sw_mute_audio);
    ui_sw_sett_mute_audio = lv_obj_get_child(cont, -1);

    lv_obj_t * sub_effects_page = lv_menu_page_create(menu, "Effects");
    lv_obj_set_style_pad_hor(sub_effects_page, menu_pad_hor, 0);
    cont = lv_menu_cont_create(sub_effects_page);
    lv_obj_set_style_pad_top(cont, 0, 0);
    lv_obj_set_style_pad_hor(cont, 0, 0);
    lv_obj_set_size(cont, lv_pct(100), lv_pct(100));
    create_effects_management_lists(cont);

    lv_obj_t * sub_presets_page = lv_menu_page_create(menu, "Presets");
    lv_obj_set_style_pad_hor(sub_presets_page, menu_pad_hor, 0);
    cont = lv_menu_cont_create(sub_presets_page);
    lv_obj_set_style_pad_top(cont, 0, 0);
    lv_obj_set_style_pad_hor(cont, 0, 0);
    lv_obj_set_size(cont, lv_pct(100), lv_pct(100));
    create_presets_management_lists(cont);

    lv_obj_t * sub_display_page = lv_menu_page_create(menu, "Display");
    lv_obj_set_style_pad_hor(sub_display_page, menu_pad_hor, 0);
    section = lv_menu_section_create(sub_display_page);
    cont = menu_create_slider(section, NULL, "Brightness", 0, 100, 100, ui_event_sld_display_brightness);
    ui_sld_sett_displ_bright = lv_obj_get_child(cont, -1);
    cont = menu_create_switch(section, NULL, "Dark mode", true, ui_event_sw_dark_mode);
    ui_sw_sett_dark_mode = lv_obj_get_child(cont, -1);

    lv_obj_t * sub_software_page = lv_menu_page_create(menu, "Software");
    lv_obj_set_style_pad_hor(sub_software_page, menu_pad_hor, 0);
    section = lv_menu_section_create(sub_software_page);
    menu_create_text(section, NULL, GIT_REVISION);

    lv_obj_t * sub_hardware_page = lv_menu_page_create(menu, "Hardware");
    lv_obj_set_style_pad_hor(sub_hardware_page, menu_pad_hor, 0);
    section = lv_menu_section_create(sub_hardware_page);
#ifdef DUAL_CORE_APP
    menu_create_text(section, NULL, "Board: STM32H745I-DISCO DKH745IO$AT2\nCPU1: ARM Cortex-M7 400MHz\nCPU2: ARM Cortex-M4 200MHz\nRAM: 8MB\nStorage: 64MB\nAudio: 24bit/48kHz\nDisplay: 480x272 RGB565");
#else
    menu_create_text(section, NULL, "Board: STM32F746G-DISCO MB1191B\nCPU: ARM Cortex-M7 200MHz\nRAM: 8MB\nStorage: 16MB\nAudio: 24bit/48kHz\nDisplay: 480x272 RGB565");
#endif
    lv_obj_t * sub_about_page = lv_menu_page_create(menu, "About");
    lv_obj_set_style_pad_hor(sub_about_page, menu_pad_hor, 0);
    cont = menu_create_text(sub_about_page, NULL, "Guitar MFX - Guitar Multi Effect Processor\nCopyright 2023 Kamil Worek. All rights reserved.");
    section = lv_menu_section_create(sub_about_page);
    cont = menu_create_text(section, NULL, "Software information");
    lv_menu_set_load_page_event(menu, cont, sub_software_page);
    cont = menu_create_text(section, NULL, "Hardware information");
    lv_menu_set_load_page_event(menu, cont, sub_hardware_page);
    cont = menu_create_text(section, NULL, "Factory reset");
    lv_obj_add_event_cb(cont, menu_factory_reset_handler, LV_EVENT_CLICKED, NULL);

    /* Create a root page */
    lv_obj_t * menu_root_page = lv_menu_page_create(menu, "Settings");
    lv_obj_set_style_pad_hor(menu_root_page, menu_pad_hor, 0);
    section = lv_menu_section_create(menu_root_page);
    cont = menu_create_text(section, LV_SYMBOL_AUDIO, "Effects");
    lv_menu_set_load_page_event(menu, cont, sub_effects_page);
    cont = menu_create_text(section, LV_SYMBOL_LIST, "Presets");
    lv_menu_set_load_page_event(menu, cont, sub_presets_page);
    cont = menu_create_text(section, LV_SYMBOL_VOLUME_MAX, "Audio");
    lv_menu_set_load_page_event(menu, cont, sub_audio_page);
    cont = menu_create_text(section, LV_SYMBOL_IMAGE, "Display");
    lv_menu_set_load_page_event(menu, cont, sub_display_page);

    lv_menu_separator_create(menu_root_page);
    section = lv_menu_section_create(menu_root_page);
    cont = menu_create_text(section, LV_SYMBOL_SETTINGS, "About");
    lv_menu_set_load_page_event(menu, cont, sub_about_page);

    lv_menu_set_sidebar_page(menu, NULL);
    lv_menu_set_page(menu, menu_root_page);

    /* Create CPU load indicator label */
    ui_lbl_sett_cpu_load = lv_label_create(menu);
    lv_obj_add_flag(ui_lbl_sett_cpu_load, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_set_align(ui_lbl_sett_cpu_load, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_pad_all(ui_lbl_sett_cpu_load, lv_obj_get_style_pad_right(lv_menu_get_main_header(menu), 0), 0);
    lv_label_set_text_fmt(ui_lbl_sett_cpu_load, "CPU load: %2u%%", 0);

    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
}
