// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "../ui.h"

#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

static void menu_exit_handler(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    lv_obj_t * menu = lv_event_get_user_data(e);

    if (lv_menu_back_btn_is_root(menu, obj))
        _ui_screen_change(&ui_settings_parent_screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, NULL);
}

static void menu_set_theme_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);

    if (code == LV_EVENT_VALUE_CHANGED)
    {
        bool dark_mode = lv_obj_has_state(obj, LV_STATE_CHECKED);

        lv_disp_t *disp = lv_disp_get_default();
        lv_color_t primary_color = lv_color_hex(UI_PALETTE_SPRING_GREEN);
        lv_color_t secondary_color = lv_color_hex(UI_PALETTE_BATTLESHIP_GRAY);
        lv_theme_t *theme = lv_theme_default_init(disp, primary_color, secondary_color, dark_mode, LV_FONT_DEFAULT);
        lv_disp_set_theme(disp, theme);

        lv_color_t menu_bg_color = dark_mode ? lv_color_lighten(lv_color_black(), 25) : lv_color_darken(lv_color_white(), 25);
        lv_obj_set_style_bg_color(ui_menu_sett, menu_bg_color, 0);
    }
}

static lv_obj_t * menu_create_text(lv_obj_t * parent, const char * icon, const char * txt)
{
    lv_obj_t * obj = lv_menu_cont_create(parent);

    lv_obj_t * img = NULL;
    lv_obj_t * label = NULL;

    if (icon)
    {
        img = lv_img_create(obj);
        lv_img_set_src(img, icon);
    }

    if (txt)
    {
        label = lv_label_create(obj);
        lv_label_set_text(label, txt);
        lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_set_flex_grow(label, 1);
    }

    return obj;
}

static lv_obj_t * menu_create_slider(lv_obj_t * parent, const char * icon, const char * txt, int32_t min, int32_t max, int32_t val, lv_event_cb_t event_cb)
{
    lv_obj_t * obj = menu_create_text(parent, icon, txt);

    lv_obj_t * slider = lv_slider_create(obj);
    lv_obj_set_flex_grow(slider, 1);
    lv_slider_set_range(slider, min, max);
    lv_slider_set_value(slider, val, LV_ANIM_OFF);

    if (icon == NULL)
        lv_obj_add_flag(slider, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);

    if (event_cb)
        lv_obj_add_event_cb(slider, event_cb, LV_EVENT_ALL, NULL);

    return obj;
}

static lv_obj_t * menu_create_switch(lv_obj_t * parent, const char * icon, const char * txt, bool chk, lv_event_cb_t event_cb)
{
    lv_obj_t * obj = menu_create_text(parent, icon, txt);

    lv_obj_t * sw = lv_switch_create(obj);
    lv_obj_add_state(sw, chk ? LV_STATE_CHECKED : 0);

    if (event_cb)
        lv_obj_add_event_cb(sw, event_cb, LV_EVENT_ALL, NULL);

    return obj;
}

static bool is_in_fx_chain(const char *name)
{
    for (unsigned i = 0; i < lv_obj_get_child_cnt(ui_list_sett_fx_chain); i++)
    {
        lv_obj_t * btn = lv_obj_get_child(ui_list_sett_fx_chain, i);
        if (strcmp(name, lv_list_get_btn_text(ui_list_sett_fx_chain, btn)) == 0)
            return true;
    }

    return false;
}

static void fx_chain_btn_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);

    if (code == LV_EVENT_CLICKED)
    {
        if (ui_btn_sett_curr_fx == obj)
            ui_btn_sett_curr_fx = NULL;
        else
            ui_btn_sett_curr_fx = obj;

        lv_obj_t * parent = lv_obj_get_parent(obj);
        for (unsigned i = 0; i < lv_obj_get_child_cnt(parent); i++)
        {
            lv_obj_t * child = lv_obj_get_child(parent, i);

            if (child == ui_btn_sett_curr_fx)
                lv_obj_clear_state(child, LV_STATE_CHECKED);
            else
                lv_obj_add_state(child, LV_STATE_CHECKED);
        }
    }
}

static void fx_ops_back_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_CLICKED)
    {
        lv_obj_clear_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_HIDDEN);
        lv_obj_del(ui_list_sett_fx_items);
    }
}

static void fx_ops_add_fx_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * fx_item = lv_event_get_target(e);

    if (code == LV_EVENT_CLICKED)
    {
        uint32_t index = lv_obj_get_child_cnt(ui_list_sett_fx_chain);

        if (ui_btn_sett_curr_fx != NULL)
            index = lv_obj_get_index(ui_btn_sett_curr_fx) + 1;

        lv_obj_t * btn = lv_btn_create(ui_list_sett_fx_chain);
        lv_obj_set_width(btn, LV_SIZE_CONTENT);
        lv_obj_set_style_text_color(btn, lv_color_black(), LV_STATE_DEFAULT);
        lv_obj_add_event_cb(btn, fx_chain_btn_handler, LV_EVENT_CLICKED, NULL);
        lv_obj_add_state(btn, LV_STATE_CHECKED);
        lv_obj_move_to_index(btn, index);
        lv_obj_scroll_to_view(btn, LV_ANIM_ON);

        lv_obj_t * lab = lv_label_create(btn);
        lv_label_set_text(lab, lv_list_get_btn_text(ui_list_sett_fx_items, fx_item));

        ui_settings_add_effect(lv_obj_get_index(fx_item) - 1, index - 1);

        lv_obj_clear_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_HIDDEN);
        lv_obj_del(ui_list_sett_fx_items);
    }
}

static void fx_ops_add_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_CLICKED)
    {
        /* Create list of available effects to add to effects chain */
        ui_list_sett_fx_items = lv_list_create(lv_obj_get_parent(ui_list_sett_fx_ops));
        lv_obj_add_flag(ui_list_sett_fx_items, LV_OBJ_FLAG_IGNORE_LAYOUT);
        lv_obj_set_size(ui_list_sett_fx_items, lv_pct(40), lv_pct(100));
        lv_obj_align(ui_list_sett_fx_items, LV_ALIGN_TOP_RIGHT, 0, 0);

        lv_obj_t * btn = lv_list_add_btn(ui_list_sett_fx_items, LV_SYMBOL_LEFT, NULL);
        lv_obj_add_event_cb(btn, fx_ops_back_handler, LV_EVENT_ALL, NULL);
        lv_group_remove_obj(btn);

        for (unsigned i = 0; i < sizeof(ui_fx_names) / sizeof(ui_fx_names[0]); i++)
        {
            btn = lv_list_add_btn(ui_list_sett_fx_items, NULL, ui_fx_names[i]);

            if (is_in_fx_chain(ui_fx_names[i]))
            {
                lv_obj_set_style_text_color(btn, lv_color_darken(lv_color_white(), 127), LV_STATE_DISABLED);
                lv_obj_add_state(btn, LV_STATE_DISABLED);
            }

            lv_obj_add_event_cb(btn, fx_ops_add_fx_handler, LV_EVENT_ALL, NULL);
            lv_group_remove_obj(btn);
        }

        lv_obj_add_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_HIDDEN);
    }
}

static void fx_ops_remove_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if ((code == LV_EVENT_CLICKED) || (code == LV_EVENT_LONG_PRESSED_REPEAT))
    {
        if (ui_btn_sett_curr_fx == NULL)
            return;

        uint32_t index = lv_obj_get_index(ui_btn_sett_curr_fx);

        for (unsigned i = 0; i < sizeof(ui_fx_names) / sizeof(ui_fx_names[0]); i++)
        {
            if (strcmp(ui_fx_names[i], lv_label_get_text(lv_obj_get_child(ui_btn_sett_curr_fx, -1))) == 0)
                ui_settings_remove_effect(i);
        }

        if (index == lv_obj_get_child_cnt(ui_list_sett_fx_chain) - 1)
            index--;

        lv_obj_del(ui_btn_sett_curr_fx);
        ui_btn_sett_curr_fx = lv_obj_get_child(ui_list_sett_fx_chain, index);

        if (ui_btn_sett_curr_fx == NULL)
            return;

        lv_obj_clear_state(ui_btn_sett_curr_fx, LV_STATE_CHECKED);
        lv_obj_move_to_index(ui_btn_sett_curr_fx, index);
        lv_obj_scroll_to_view(ui_btn_sett_curr_fx, LV_ANIM_ON);
    }
}

static void fx_ops_move_up_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if ((code == LV_EVENT_CLICKED) || (code == LV_EVENT_LONG_PRESSED_REPEAT))
    {
        if (ui_btn_sett_curr_fx == NULL)
            return;

        const uint32_t index = lv_obj_get_index(ui_btn_sett_curr_fx);

        ui_settings_move_effect(index, 1);

        if (index <= 0)
            return;

        lv_obj_move_to_index(ui_btn_sett_curr_fx, index - 1);
        lv_obj_scroll_to_view(ui_btn_sett_curr_fx, LV_ANIM_ON);
    }
}

static void fx_ops_move_down_handler(lv_event_t * e)
{
    const lv_event_code_t code = lv_event_get_code(e);

    if ((code == LV_EVENT_CLICKED) || (code == LV_EVENT_LONG_PRESSED_REPEAT))
    {
        if (ui_btn_sett_curr_fx == NULL)
            return;

        const uint32_t index = lv_obj_get_index(ui_btn_sett_curr_fx);

        ui_settings_move_effect(index, -1);

        lv_obj_move_to_index(ui_btn_sett_curr_fx, index + 1);
        lv_obj_scroll_to_view(ui_btn_sett_curr_fx, LV_ANIM_ON);

    }
}

static void create_effects_management_lists(lv_obj_t * parent)
{
    ui_btn_sett_curr_fx = NULL;

    /* Create a list of effects in chain */
    ui_list_sett_fx_chain = lv_list_create(parent);
    lv_obj_add_flag(ui_list_sett_fx_chain, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_set_style_pad_row(ui_list_sett_fx_chain, 5, 0);
    lv_obj_set_size(ui_list_sett_fx_chain, lv_pct(58), lv_pct(100));
    lv_obj_align(ui_list_sett_fx_chain, LV_ALIGN_TOP_LEFT, 0, 0);

    /* Create a second list with buttons for various operations on effects chain */
    ui_list_sett_fx_ops = lv_list_create(parent);
    lv_obj_add_flag(ui_list_sett_fx_ops, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_set_size(ui_list_sett_fx_ops, lv_pct(40), LV_SIZE_CONTENT);
    lv_obj_align(ui_list_sett_fx_ops, LV_ALIGN_TOP_RIGHT, 0, 0);

    lv_obj_t * btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_PLUS, "Add...");
    lv_obj_add_event_cb(btn, fx_ops_add_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_TRASH, "Remove");
    lv_obj_add_event_cb(btn, fx_ops_remove_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_UP, "Move up");
    lv_obj_add_event_cb(btn, fx_ops_move_up_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(ui_list_sett_fx_ops, LV_SYMBOL_DOWN, "Move down");
    lv_obj_add_event_cb(btn, fx_ops_move_down_handler, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);
}

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);

    /* Create menu */
    lv_obj_t * menu = lv_menu_create(ui_settings);

    lv_obj_set_style_bg_color(menu, lv_color_lighten(lv_color_black(), 25), 0);
    lv_menu_set_mode_root_back_btn(menu, LV_MENU_ROOT_BACK_BTN_ENABLED);
    lv_obj_add_event_cb(menu, menu_exit_handler, LV_EVENT_CLICKED, menu);
    lv_obj_set_size(menu, lv_pct(100), lv_pct(100));
    lv_obj_center(menu);
    ui_menu_sett = menu;

    /* Modify the back button */
    lv_obj_t * back_btn = lv_menu_get_main_header_back_btn(menu);
    lv_obj_set_style_pad_hor(back_btn, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);

    lv_obj_t * cont;
    lv_obj_t * section;

    /* Create sub pages */
    lv_obj_t * sub_audio_page = lv_menu_page_create(menu, "Audio");
    lv_obj_set_style_pad_hor(sub_audio_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(sub_audio_page);
    cont = menu_create_slider(section, NULL, "Input volume", 0, 31, 11, ui_event_sld_in_vol);
    ui_sld_sett_in_vol = lv_obj_get_child(cont, -1);
    cont = menu_create_slider(section, NULL, "Output volume", 0, 63, 57, ui_event_sld_out_vol);
    ui_sld_sett_out_vol = lv_obj_get_child(cont, -1);
    cont = menu_create_switch(section, NULL, "Mute", false, ui_event_sw_mute_audio);
    ui_sw_sett_mute_audio = lv_obj_get_child(cont, -1);

    lv_obj_t * sub_effects_page = lv_menu_page_create(menu, "Effects");
    lv_obj_set_style_pad_hor(sub_effects_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    cont = lv_menu_cont_create(sub_effects_page);
    lv_obj_set_style_pad_top(cont, 0, 0);
    lv_obj_set_style_pad_hor(cont, 0, 0);
    lv_obj_set_size(cont, lv_pct(100), lv_pct(100));
    create_effects_management_lists(cont);

    lv_obj_t * sub_presets_page = lv_menu_page_create(menu, "Presets");
    lv_obj_set_style_pad_hor(sub_presets_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(sub_presets_page);
    menu_create_text(section, NULL, "Load preset");
    menu_create_text(section, NULL, "Save preset");
    menu_create_text(section, NULL, "Remove all");

    lv_obj_t * sub_display_page = lv_menu_page_create(menu, "Display");
    lv_obj_set_style_pad_hor(sub_display_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(sub_display_page);
    menu_create_slider(section, NULL, "Brightness", 0, 150, 100, NULL);
    cont = menu_create_switch(section, NULL, "Dark mode", true, menu_set_theme_handler);

    lv_obj_t * sub_software_page = lv_menu_page_create(menu, "Software");
    lv_obj_set_style_pad_hor(sub_software_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(sub_software_page);
    menu_create_text(section, NULL, "Version: v1.0.0");

    lv_obj_t * sub_hardware_page = lv_menu_page_create(menu, "Hardware");
    lv_obj_set_style_pad_hor(sub_hardware_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(sub_hardware_page);
    menu_create_text(section, NULL, "Version: v1.0.1\nCPU: ARM Cortex-M7 200MHz\nRAM: 8MB");

    lv_obj_t * sub_about_page = lv_menu_page_create(menu, "About");
    lv_obj_set_style_pad_hor(sub_about_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    cont = menu_create_text(sub_about_page, NULL, "Guitar MFX - Guitar Multi Effect Processor\nCopyright 2023 Kamil Worek. All rights reserved.");
    section = lv_menu_section_create(sub_about_page);
    cont = menu_create_text(section, NULL, "Software information");
    lv_menu_set_load_page_event(menu, cont, sub_software_page);
    cont = menu_create_text(section, NULL, "Hardware information");
    lv_menu_set_load_page_event(menu, cont, sub_hardware_page);

    /* Create a root page */
    lv_obj_t * menu_root_page = lv_menu_page_create(menu, "Settings");
    lv_obj_set_style_pad_hor(menu_root_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(menu_root_page);
    cont = menu_create_text(section, LV_SYMBOL_AUDIO, "Effects");
    lv_menu_set_load_page_event(menu, cont, sub_effects_page);
    cont = menu_create_text(section, LV_SYMBOL_LIST, "Presets");
    lv_menu_set_load_page_event(menu, cont, sub_presets_page);
    cont = menu_create_text(section, LV_SYMBOL_VOLUME_MAX, "Audio");
    lv_menu_set_load_page_event(menu, cont, sub_audio_page);
    cont = menu_create_text(section, LV_SYMBOL_IMAGE, "Display");
    lv_menu_set_load_page_event(menu, cont, sub_display_page);

    lv_menu_separator_create(menu_root_page);
    section = lv_menu_section_create(menu_root_page);
    cont = menu_create_text(section, LV_SYMBOL_SETTINGS, "About");
    lv_menu_set_load_page_event(menu, cont, sub_about_page);

    lv_menu_set_sidebar_page(menu, NULL);
    lv_menu_set_page(menu, menu_root_page);

    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
}
