// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_fx_equalizer
void ui_fx_equalizer_screen_init(void);
void ui_event_fx_equalizer(lv_event_t * e);
lv_obj_t * ui_fx_equalizer;
lv_obj_t * ui_lbl_fx_name_1;
void ui_event_btn_eq_bypass(lv_event_t * e);
lv_obj_t * ui_btn_eq_bypass;
lv_obj_t * ui_lbl_eq_bypass_btn;

// SCREEN: ui_fx_noise_gate
void ui_fx_noise_gate_screen_init(void);
void ui_event_fx_noise_gate(lv_event_t * e);
lv_obj_t * ui_fx_noise_gate;
lv_obj_t * ui_lbl_fx_name_2;
void ui_event_btn_noise_gate_bypass(lv_event_t * e);
lv_obj_t * ui_btn_noise_gate_bypass;
lv_obj_t * ui_lbl_noise_gate_bypass_btn;

// SCREEN: ui_fx_tremolo
void ui_fx_tremolo_screen_init(void);
void ui_event_fx_tremolo(lv_event_t * e);
lv_obj_t * ui_fx_tremolo;
lv_obj_t * ui_background;
lv_obj_t * ui_content_group;
lv_obj_t * ui_controls_group;
lv_obj_t * ui_rate_group;
lv_obj_t * ui_Image2;
void ui_event_Arc1(lv_event_t * e);
lv_obj_t * ui_Arc1;
lv_obj_t * ui_lbl_rate;
lv_obj_t * ui_shape_group;
lv_obj_t * ui_lbl_shape;
void ui_event_sw_shape(lv_event_t * e);
lv_obj_t * ui_sw_shape;
lv_obj_t * ui_lbl_triangle;
lv_obj_t * ui_lbl_sine;
lv_obj_t * ui_depth_group;
lv_obj_t * ui_Image4;
void ui_event_Arc3(lv_event_t * e);
lv_obj_t * ui_Arc3;
lv_obj_t * ui_lbl_depth;
lv_obj_t * ui_lbl_fx_name3;
void ui_event_btn_tremolo_bypass(lv_event_t * e);
lv_obj_t * ui_btn_tremolo_bypass;
lv_obj_t * ui_lbl_tremolo_bypass_btn;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_fx_equalizer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_fx_noise_gate, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_fx_noise_gate_screen_init);
    }
}
void ui_event_btn_eq_bypass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_equalizer_bypass(e);
    }
}
void ui_event_fx_noise_gate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_fx_tremolo, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_fx_tremolo_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_fx_equalizer, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_fx_equalizer_screen_init);
    }
}
void ui_event_btn_noise_gate_bypass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_noise_gate_bypass(e);
    }
}
void ui_event_fx_tremolo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_fx_noise_gate, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_fx_noise_gate_screen_init);
    }
}
void ui_event_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_tremolo_rate_changed(e);
    }
}
void ui_event_sw_shape(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_tremolo_shape_changed(e);
    }
}
void ui_event_Arc3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_tremolo_depth_changed(e);
    }
}
void ui_event_btn_tremolo_bypass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_tremolo_bypass(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_fx_equalizer_screen_init();
    ui_fx_noise_gate_screen_init();
    ui_fx_tremolo_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_fx_tremolo);
}
