// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#ifndef _GMFX_UI_H
#define _GMFX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libs/lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void splashfadein_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_splash
void ui_splash_screen_init(void);
void ui_event_splash(lv_event_t * e);
extern lv_obj_t * ui_splash;
extern lv_obj_t * ui_lbl_splash;
// SCREEN: ui_fx_tremolo
void ui_fx_tremolo_screen_init(void);
void ui_event_fx_tremolo(lv_event_t * e);
extern lv_obj_t * ui_fx_tremolo;
extern lv_obj_t * ui_lbl_trem_fx_name;
void ui_event_btn_trem_bypass(lv_event_t * e);
extern lv_obj_t * ui_btn_trem_bypass;
extern lv_obj_t * ui_lbl_btn_trem_bypass_;
extern lv_obj_t * ui_pnl_trem_controls;
extern lv_obj_t * ui_pnl_trem_rate;
extern lv_obj_t * ui_img_trem_rate;
void ui_event_arc_trem_rate(lv_event_t * e);
extern lv_obj_t * ui_arc_trem_rate;
extern lv_obj_t * ui_lbl_trem_rate;
extern lv_obj_t * ui_pnl_trem_depth;
extern lv_obj_t * ui_img_trem_depth;
void ui_event_arc_trem_depth(lv_event_t * e);
extern lv_obj_t * ui_arc_trem_depth;
extern lv_obj_t * ui_lbl_trem_depth;
extern lv_obj_t * ui_pnl_trem_shape;
extern lv_obj_t * ui_lbl_trem_shape;
void ui_event_sw_tremolo_shape(lv_event_t * e);
extern lv_obj_t * ui_sw_tremolo_shape;
extern lv_obj_t * ui_lbl_trem_triangle;
extern lv_obj_t * ui_lbl_trem_sine;
// SCREEN: ui_fx_equalizer
void ui_fx_equalizer_screen_init(void);
void ui_event_fx_equalizer(lv_event_t * e);
extern lv_obj_t * ui_fx_equalizer;
extern lv_obj_t * ui_lbl_eq_fx_name;
void ui_event_btn_eq_bypass(lv_event_t * e);
extern lv_obj_t * ui_btn_eq_bypass;
extern lv_obj_t * ui_lbl_btn_eq_bypass;
// SCREEN: ui_fx_noise_gate
void ui_fx_noise_gate_screen_init(void);
void ui_event_fx_noise_gate(lv_event_t * e);
extern lv_obj_t * ui_fx_noise_gate;
extern lv_obj_t * ui_lbl_ng_fx_name;
void ui_event_btn_ng_bypass(lv_event_t * e);
extern lv_obj_t * ui_btn_ng_bypass;
extern lv_obj_t * ui_lbl_btn_ng_bypass;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_btn_1_inact_png);    // assets/btn_1_inact.png
LV_IMG_DECLARE(ui_img_btn_1_act_png);    // assets/btn_1_act.png
LV_IMG_DECLARE(ui_img_btn_knob_png);    // assets/btn_knob.png

LV_FONT_DECLARE(ui_font_14_bold);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
