// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gmfx

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_equalizer_bypass(lv_event_t * e);
void ui_noise_gate_bypass(lv_event_t * e);
void ui_tremolo_rate_changed(lv_event_t * e);
void ui_tremolo_shape_changed(lv_event_t * e);
void ui_tremolo_depth_changed(lv_event_t * e);
void ui_tremolo_bypass(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
